### ISSUE TITLE
TypeError: signer.sign is not a function

### ISSUE THREAD

**Issue by GuasaPlay** [vbuch/node-signpdf#105]
Hi everyone, I am trying to implement this package following the example [here](https://github.com/vbuch/node-signpdf/blob/14b1b84bea952ff7c9d4847bf7d77cab28cbd09e/src/signpdf.test.js#L242), but I really don't know how to do it. I am a newbie in this topic, please help me how could I do it. This is my code:
```
const fs = require("fs");
const signer = require("node-signpdf");

const pdfBuffer = fs.readFileSync("./firmas/ejemplo.pdf");
const p12Buffer = fs.readFileSync("./firmas/carmen_raquel_barreto_arias.p12");

const password = "*******";

let resp = signer.sign(pdfBuffer, p12Buffer, {
  passphrase: password,
});

console.log(resp);

```

And this is the error it shows me:
```
TypeError: signer.sign is not a function
    at Object.<anonymous> (C:\Users\oscar\Desktop\PROYECTOS\sign-prueba\index.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```
@NoahCardoza, maybe you can help me with this?

**Comment by NoahCardoza** [comment]
Take a look at [this file](https://github.com/NoahCardoza/node-signpdf-bug/blob/main/test.fillable.node-signpdf.js). The issue is that they are using ES6 import/exports which end up exporting everything into the `.default` property.

To correctly import/use the module try:

```js
const signer = require('node-signpdf').default;

signer.sign(...)
```

**Comment by GuasaPlay** [comment]
@NoahCardoza thanks it already worked. But now when I go to check if the PDF is signed it shows me that:

The signature is NOT VALID
- The document has not been modified since the signature was applied.
- The identity of the signer is not valid

And then if I go to the details of the signature it shows me the following:
The signature was created with Not available
Hash algorithm: SHA256
Signature algorithm: rsaEnvryption-pcks1.

Maybe you know something about this?

**Comment by NoahCardoza** [comment]
Interesting... Try generating your own psk12 store and see if that works?

**Comment by vbuch** [comment]
https://www.adobe.com/devnet-docs/etk_deprecated/tools/QuickKeys/Acrobat_SignatureValidationKey.pdf
