### ISSUE TITLE
Information about the pdf orientation gets lost, impossible to sign a pdf in "landscape" mode

### ISSUE THREAD

**Issue by fleetster** [vbuch/node-signpdf#108]
**Describe the bug and the expected behaviour**
the page orientation is missing when signing the document. The pages are always in "portrait" mode, even when creating the pdf in "landscape" mode

**Is it a bug in signing or in the helpers?**
It could be introduced by `plainAddPlaceholder`

**To Reproduce**
Hi,  
I am generating a pdf from HTML using the library `html-pdf`. When creating the document, I pass the option `orientation:'landscape'` that rotates the orientation of the page. If I open the pdf generated by this library, everything looks like it should be.  
I have recently had the necessity to sign the document, so we started using your library.  

1. First we read the pdf previously generated:

`const pdfBuffer = await fs.readFile(path.join(fileDir, fileName));`

2. Then we add the placeholder:

`const pdfBufferWithPlaceholder = plainAddPlaceholder({pdfBuffer, reason: 'reason'});`

3. And in the end we sign the document:

`const signedPdfBuffer = Signer.sign(pdfBufferWithPlaceholder, p12Cert, {passphrase});`

4. The resulting pdf is properly signed but the orientation of the document is "portrait" and not "landscape". It looks like the information of the orientation got lost in the signing process, or when adding the placeholder.

Thanks in advance for the support!

**Comment by cassiobt** [comment]
I was using [https://github.com/marcbachmann/node-html-pdf](url) to generate the PDF. 
So I change to[https://github.com/mrafiqk/html-pdf-node](url) and now it works like a charm

**Comment by vbuch** [comment]
@fleetster while I trust you that this is reproducible, "I am generating a pdf from HTML using the library html-pdf." is not something I can easily reproduce. Could you add a file as generated by that library so that I can possibly test what and where gets broken?
