### ISSUE TITLE
The signed.pdf will not open in Acrobat reader

### ISSUE THREAD

**Issue by jbeuckm** [vbuch/node-signpdf#109]
Error message: "An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem." and "At least one signature has problems."

**To Reproduce**
1. Generate self-signed p12 file (no password):
```
openssl req -new -key myKey.pem -out cert.csr
openssl x509 -req -in cert.csr -signkey myKey.pem -out cert.crt
openssl pkcs12 -export -in cert.crt -inkey myKey.pem -out cert.p12
```

2. Add placeholder and sign PDF
```
const pdfBuffer = fs.readFileSync('./test.pdf')

const pdfBufferWithPlaceholder = plainAddPlaceholder({
  pdfBuffer,
  reason: 'Signing the pdf.',
  signatureLength: 3300,
})

const signedPdf = signer.sign(pdfBufferWithPlaceholder, fs.readFileSync('./keyStore.p12'))
fs.writeFileSync('signed.pdf', signedPdf)
```

3. Check signature with `pdfsig`
```
➜  $ pdfsig ./signed.pdf
Internal Error (0): couldn't find default Firefox Folder
Digital Signature Info of: ./signed.pdf
Signature #1:
  - Signer Certificate Common Name: com.testco.abc123
  - Signer full Distinguished Name: E=joe@beigerecords.com,CN=com.testco.abc123,O=Test Co,L=St. Paul,ST=Minnesota,C=us
  - Signing Time: Dec 01 2020 23:32:59
  - Signing Hash Algorithm: SHA-256
  - Signature Type: adbe.pkcs7.detached
  - Signed Ranges: [0 - 1206821], [1213423 - 1214226]
  - Total document signed
  - Signature Validation: Signature is Valid.
  - Certificate Validation: Certificate issuer is unknown.
```
[signed.pdf](https://github.com/vbuch/node-signpdf/files/5627207/signed.pdf)

**Comment by vbuch** [comment]
Can't remember on top of my head if the trailer must always contain the full reftable. The initial version has a huge trailer, the signed one has a small one with lots of skipped numbers. But... I seem to have some memory that only overridden entries are mandatory in the updated version. I need to check if that's correct. Chrome's PDF reader seems to do alright with the file but it doesn't care of signatures. LiberOffice Draw shows some malformed version of the doc and shows there is a signature but can't show signature's details. So... yes, there is an issue with the file. If I happen to have some time, I'll check deeper.

**Comment by MallRoy** [comment]
I am also facing the same issue. do we have any workaround for this?
