### ISSUE TITLE
Invalid signature on Adobe Reader: "signer's identity has not yet been verified"

### ISSUE THREAD

**Issue by dody87** [vbuch/node-signpdf#111]
I've tried with several p12 certificates and when I sign via my Nodejs approach it returns an invalid signature on Adobe.

![Screen Shot 2020-12-16 at 19 28 43](https://user-images.githubusercontent.com/3058417/102414231-ec006e80-3fd4-11eb-907a-d924c25737bf.png)

However, signing just with Adobe the signature seems to be valid (just with a warning).

![Screen Shot 2020-12-16 at 19 29 27](https://user-images.githubusercontent.com/3058417/102414285-063a4c80-3fd5-11eb-8f7e-ad31a254bcc1.png)

Is there something that I'm missing?

`
const signer = require('node-signpdf')
const fs = require('fs')
const helpers = require('node-signpdf/dist/helpers')

const init = async () => {
    const p12Buffer = fs.readFileSync(`${__dirname}/cert.p12`);

    let pdfBuffer = fs.readFileSync(`${__dirname}/test.pdf`);
    pdfBuffer = helpers.plainAddPlaceholder({
        pdfBuffer,
        signatureLength: 3224,
    });

    pdfBuffer = signer.default.sign(pdfBuffer, p12Buffer, {
        passphrase: 'reingenio'
    });

    fs.writeFileSync(`${__dirname}/signed.pdf`, pdfBuffer)
}

init()
`

Thanks.

**Comment by inane** [comment]
Same problem here

**Comment by LuanMaik** [comment]
Check this: https://github.com/vizicsaba89/pdf-signer/issues/22

**Comment by inane** [comment]
> Check this: [vizicsaba89/pdf-signer#22](https://github.com/vizicsaba89/pdf-signer/issues/22)

Yes, I checked that link some weeks ago, even I contacted with the guy. No news.

**Comment by FranckDepoortere** [comment]
Hello,

If we use a certificate with English description, without accented characters, it works for us.
We encounter the same issue with Spanish certificates containing accented characters.
Actually in most of cases, languages like Spanish, or other latin languages often contains accented characters within the certificate.
Example in Spanish: "CN = AC Representación"
In consequence, the signature doesn't work for these latin languages.

We are blocked.
Thanks in advance you for your help
Franck

**Comment by LuanMaik** [comment]
@FranckDepoortere , what does happen if you try to use some encode convert on certificate content before use it?
Example:

```javascript
// try to use converted to UTF8
const certificateContentEncoded = Buffer.from(certificateContent, 'utf-8');

// or  try to use converted to iso-8859-1
const certificateContentEncoded = Buffer.from(certificateContent, 'iso-8859-1');


// .. use the certificate content encoded
```

**Comment by bopos** [comment]
Hello,
  I use directly the p12 (binary) file and I have the same issue when the certificate include accented characters
```
import signer from 'node-signpdf';
...
const signedPdf = signer.sign(
  fs.readFileSync(PATH_TO_PDF_FILE)
  fs.readFileSync(PATH_TO_P12_CERTIFICATE),
);
```

**Comment by FranckDepoortere** [comment]
Hello, 

Apparently, the bug is not located in the library 'node-signpdf', but on 'forge' lib.

This PR fixed our issue: 
https://github.com/digitalbazaar/forge/pull/731/files
(@bopos  found this)
Unfortunately, this PR has not been merged yet. It has been created in nov 2019.
Thank you anyway.
Franck

**Comment by Arturokin** [comment]
any update on this? i'm having de the same issue

**Comment by AgustinVillagran** [comment]
Hi! Has somebody found a workaround for this issue? The PR is still open.
