### ISSUE TITLE
[Question] - Can I signing this pdf with encrypted (Password protected)

### ISSUE THREAD

**Issue by chayakornjj** [vbuch/node-signpdf#117]
Question

- Is that anyway or any recommendation to sign protected pdf (PDF With password) with this lib?

Thank you :-)

**Comment by kevinbeal** [comment]
Does this work?

`signer.sign(pdfBuffer, p12Buffer, {passphrase:"your-password")`

**Comment by chayakornjj** [comment]
@kevinbeal Not sure yet will try. Actually i made this work with other programing language (Java, PDFBOX). But happy to try with this package.

**Comment by ZaunSupremoXV** [comment]
@chayakornjj This function is used to sign a PDF with a digital certificate that has a password.

@chayakornjj Essa função serve para assinar um PDF com um certificado digital que possui senha.

**Comment by vbuch** [comment]
Yeah, @kevinbeal 's way is not what @chayakornjj is looking for. Passphrase is the password of the P12, not one in the PDF.

**Comment by chayakornjj** [comment]
Thanks guys seem like passphrase is for P12 file password not for PDF password.

**Comment by KristophrAlves** [comment]
> Does this work?
> 
> ```js
> signer.sign(pfBuffer, p12Buffer, { passphrase: "your-password" })
> ```

it helped me, thanks!
