### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by ninepi09** [vbuch/node-signpdf#121]
```
const pdf = await readAsArrayBuffer(pdfFile);

      const res = await fetch(proxyurl+p12File);
      const p12Blob = await res.blob();

      // const p12Buffer = fs.readFileSync(`${__dirname}/../resources/certificate.p12`);
      //   let pdfBuffer = fs.readFileSync(`${__dirname}/../resources/including-a-link.pdf`);
  
      console.log("saving");
      console.log("pdf name ", pdfFile);

      const p12Buffer = await readAsArrayBuffer(p12Blob);
        // pdfBuffer = plainAddPlaceholder({
        //     pdfBuffer,
        //     reason: 'I have reviewed it.',
        //     signatureLength: 1612,
        // });
        // signer.sign(pdf, p12Buffer);
        const signedPdf = signer.sign(pdf, p12Buffer);
        const {signature, signedData} = extractSignature(signedPdf);
        expect(typeof signature === 'string').toBe(true);
        expect(signedData instanceof Buffer).toBe(true);
```

i use that code and have import signer from 'node-signpdf'; on <script> tag svelte file . 

i got this error : ReferenceError: Buffer is not defined

what is wrong with my code?

**Comment by kevinbeal** [comment]
You're doing it in a browser. This is a node-specific library.

**Comment by ZaunSupremoXV** [comment]
```
const signer = require('node-signpdf').default
const fs = require('fs')
const { plainAddPlaceholder } = require('node-signpdf/dist/helpers');


        const filename = '${__dirname}/../resources/including-a-link.pdf'
        const cert = '${__dirname}/../resources/certificate.p12'
        try {
            var output = plainAddPlaceholder({
                pdfBuffer: fs.readFileSync(filename),
                reason: 'My Sign',
                signatureLength: 8192
            });
        } catch (e) {
            console.log('Error during adding placeholder');
            console.log(e.message);
            return response
                .status(500)
                .send({
                    message: 'Error during adding placeholder',
                    fn: plainAddPlaceholder ? plainAddPlaceholder.toString() : '-',
                    error: e.message,
                    trace: JSON.stringify(e.trace)
                });
        }
        try {
            const signedPdf = signer.sign(output, fs.readFileSync(cert), { passphrase: 'PASSWORD P12 OR PFX', asn1StrictParsing: true });
            fs.writeFileSync(__dirname + '/last.pdf', signedPdf);
            fs.writeFileSync(filename, signedPdf);
            const { signature, signedData } = extractSignature(signedPdf);
            console.log(`Successfully signed ${filename}`);
            return response
                .send({ message: 'ok' });
        } catch (e) {
            console.log('Error during singing PDF');
            console.log(e.message);
            return response
                .status(500)
                .send({
                    message: 'Error during singing PDF',
                    error: e.message,
                    trace: JSON.stringify(e.trace)
                });
        }

```

**Comment by ZaunSupremoXV** [comment]
> ```
> const signer = require('node-signpdf').default
> const fs = require('fs')
> const { plainAddPlaceholder } = require('node-signpdf/dist/helpers');
> 
> 
>         const filename = '${__dirname}/../resources/including-a-link.pdf'
>         const cert = '${__dirname}/../resources/certificate.p12'
>         try {
>             var output = plainAddPlaceholder({
>                 pdfBuffer: fs.readFileSync(filename),
>                 reason: 'My Sign',
>                 signatureLength: 8192
>             });
>         } catch (e) {
>             console.log('Error during adding placeholder');
>             console.log(e.message);
>             return response
>                 .status(500)
>                 .send({
>                     message: 'Error during adding placeholder',
>                     fn: plainAddPlaceholder ? plainAddPlaceholder.toString() : '-',
>                     error: e.message,
>                     trace: JSON.stringify(e.trace)
>                 });
>         }
>         try {
>             const signedPdf = signer.sign(output, fs.readFileSync(cert), { passphrase: 'PASSWORD P12 OR PFX', asn1StrictParsing: true });
>             fs.writeFileSync(__dirname + '/last.pdf', signedPdf);
>             fs.writeFileSync(filename, signedPdf);
>             const { signature, signedData } = extractSignature(signedPdf);
>             console.log(`Successfully signed ${filename}`);
>             return response
>                 .send({ message: 'ok' });
>         } catch (e) {
>             console.log('Error during singing PDF');
>             console.log(e.message);
>             return response
>                 .status(500)
>                 .send({
>                     message: 'Error during singing PDF',
>                     error: e.message,
>                     trace: JSON.stringify(e.trace)
>                 });
>         }
> ```

That way it usually works to adapt to a post using the express or adonis.
