### ISSUE TITLE
I want to know how to sign to the second page? How to set it.  Existing pdf

### ISSUE THREAD

**Issue by tonglin98** [vbuch/node-signpdf#123]
I can only sign on the first page now

I tried a lot of parameters, but they couldn't be signed on the second page

Can you tell me, I will thank you very much

**Comment by vbuch** [comment]
But ... You are not signing pages. You are signing the document as a whole. You may or may not place a visible signature mark on any page you want. In the [demo with pdfkit](https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/pdfkitAddPlaceholder.js#L91) we do it on the page you are currently working on. And this is where we do it [with plainAddPlaceholder](https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/plainAddPlaceholder/index.js#L102). The default implementation only adds invisible signatures.

**Comment by tonglin98** [comment]
I have an existing PDF file
This PDF file has two pages and no placeholders
I want to put a signature on both pages
And both signatures are visible
Can this library do it ?

**Comment by tonglin98** [comment]
In short, I want to use  **plainAddPlaceholder**  to place a visible signature on the second page

**Comment by tonglin98** [comment]
> But ... You are not signing pages. You are signing the document as a whole. You may or may not place a visible signature mark on any page you want. In the [demo with pdfkit](https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/pdfkitAddPlaceholder.js#L91) we do it on the page you are currently working on. And this is where we do it [with plainAddPlaceholder](https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/plainAddPlaceholder/index.js#L102). The default implementation only adds invisible signatures.

In short, I want to use plainAddPlaceholder to place a visible signature on the second page

**Comment by vbuch** [comment]
plainAddPlaceholder's purpose is to add a the signature placeholder. So far noone created a helper or other utility to add visible widgets. In my experience I've only added widgets to a single page (either first or last). Since signatures sign whole documents, it never made sense for my usecases to do it on every page. Not sure if it is possible to link the same widget on multiple pages.

**Comment by tonglin98** [comment]
> plainAddPlaceholder的目的是添加签名占位符。到目前为止，还没有人创建帮助程序或其他实用程序来添加可见的小部件。根据我的经验，我仅将小部件添加到单个页面（第一页或最后一页）。由于签名是对整个文档进行签名的，所以我的用例在每个页面上都没有用。不知道是否可以在多个页面上链接相同的窗口小部件。



> plainAddPlaceholder's purpose is to add a the signature placeholder. So far noone created a helper or other utility to add visible widgets. In my experience I've only added widgets to a single page (either first or last). Since signatures sign whole documents, it never made sense for my usecases to do it on every page. Not sure if it is possible to link the same widget on multiple pages.

As I've tried, it's possible to add multiple visible signature fields on the same page
However, my goal is to add to the last page, can you tell me how to add to the last page?

**Comment by tonglin98** [comment]
> plainAddPlaceholder's purpose is to add a the signature placeholder. So far noone created a helper or other utility to add visible widgets. In my experience I've only added widgets to a single page (either first or last). Since signatures sign whole documents, it never made sense for my usecases to do it on every page. Not sure if it is possible to link the same widget on multiple pages.
> 
> Edit: I just read the code. Seems to me that it should be possible to link the same widget to multiple pages. You can try it. Easiest would be to run the tests and modify a test. Make one of the pdfs multi-page and cycling throught the pages [add Annots](https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/pdfkitAddPlaceholder.js#L91) to every one of them. Looks like it should be possible. Try it.

The location of the signature is on the first page by default. However, I want the location of the signature on the last page. Is there any good way?

**Comment by vbuch** [comment]
Which one are you using? plain or pdfkit? In plain, this is where the page is "selected". https://github.com/vbuch/node-signpdf/blob/14b1b84bea952ff7c9d4847bf7d77cab28cbd09e/src/helpers/plainAddPlaceholder/index.js#L40

**Comment by tonglin98** [comment]
> Which one are you using? plain or pdfkit? In plain, this is where the page is "selected".


I use plain
How to set it to the last page ?

**Comment by tonglin98** [comment]
> Which one are you using? plain or pdfkit? In plain, this is where the page is "selected".
> 
> https://github.com/vbuch/node-signpdf/blob/14b1b84bea952ff7c9d4847bf7d77cab28cbd09e/src/helpers/plainAddPlaceholder/index.js#L40

hei

**Comment by kiranbangar5946** [comment]
hey @tonglin98 can you please help me with the placeholder not visible issue,It would be great for me

**Comment by RaviTeja-clone** [comment]
@tonglin98 @vbuch  How do I select nth page in the pdf ?
