### ISSUE TITLE
[HELP] Adding Timestamps to PDFs

### ISSUE THREAD

**Issue by alexhaegler** [vbuch/node-signpdf#124]
Hello everyone,

first of all: thank you for this great piece of work!

To verify that the content of the PDF was unchanged, we would like to add a timestamp to our documents. The timestamp is created by using https://www.npmjs.com/package/openssl-nodejs to create the request which get's then sent to freetsa.org.

This returns a Time Stamp Response which we would then like to add to our PDF. 

Does anyone know how this could be achieved?

Thanks in advance for every hint!

Best

**Comment by vbuch** [comment]
See here: https://github.com/vbuch/node-signpdf/issues/68

**Comment by vbuch** [comment]
Additionally people just bumped this one: https://github.com/vbuch/node-signpdf/pull/103 There may be some valuable effort there. Worth checking.
