### ISSUE TITLE
How can I import the plainAddPlaceholder helper in my project after I installed your package?

### ISSUE THREAD

**Issue by megalypse** [vbuch/node-signpdf#126]
**Describe the bug and the expected behaviour**
I'm using this package on a typescript project, and I'm trying to sign an already existing PDF.

**Is it a bug in signing or in the helpers?**
I would like to know how I can import the plainAddPlaceholder() helper and use it in my project.

I can't find it anywhere in the 'node-signpdf' import I did.

**Comment by vbuch** [comment]
Check the files in the dist folder: https://github.com/vbuch/node-signpdf/tree/develop/dist The helpers are not exported from the root. You may need to add add 'dist' to the import path. something like 'node-sginpdf/dist/helpers/plainAddPlaceholder'

**Comment by megalypse** [comment]
```
  const pdfBuffer = await pdf.create(document, options);
  const keyBuffer = fs.readFileSync('src/certs/certificate.p12');
  const preReadyPdf = plainAddPlaceHolder({
    pdfBuffer,
    reason: 'Test',
    signatureLength: keyBuffer.length
  })

  const signedPdf = signer.sign(pdfBuffer, keyBuffer)
```

I managed to import the helper just as you said, but even using it I still get this error message:

Error: No ByteRangeStrings found within PDF buffer
    at findByteRange (D:\Projetos\Typescript\PdfGeneratorV2\node_modules\node-signpdf\dist\helpers\findByteRange.js:28:11)
    at SignPdf.sign (D:\Projetos\Typescript\PdfGeneratorV2\node_modules\node-signpdf\dist\signpdf.js:50:36)
    at generateNotificationPdf (D:\Projetos\Typescript\PdfGeneratorV2\src\index.ts:38:43)

**Comment by vbuch** [comment]
You're signing `pdfBuffer` while you've added the placeholder to `preReadyPdf` hence `No ByteRangeStrings found within PDF buffer`

**Comment by megalypse** [comment]
Oh, and what am I doing wrong?
I did just like I saw on the example below: 

```
it('signs a ready pdf', async () => {
        const p12Buffer = fs.readFileSync(`${__dirname}/../resources/certificate.p12`);
        let pdfBuffer = fs.readFileSync(`${__dirname}/../resources/w3dummy.pdf`);
        pdfBuffer = plainAddPlaceholder({
            pdfBuffer,
            reason: 'I have reviewed it.',
            signatureLength: 1612,
        });
        pdfBuffer = signer.sign(pdfBuffer, p12Buffer);

      ...
    });
```

**Comment by megalypse** [comment]
Thanks
