### ISSUE TITLE
[HELP] Sign pdf with x509

### ISSUE THREAD

**Issue by hrodrigues1984** [vbuch/node-signpdf#130]
Hello,

Thanks in advance for your work, the library is very very nice.

I tried to use an x509 certificate to sign a pdf without the private key. Can you help with this challenge?
After a lot of digging and using the library as a starting point, I was able to overcome some issues by changing the default p12 approach to be compatible with x509. Also related to node-forge, for instance, since I don't have access to the private key the pkcs7 object needs to use 'encrypt' instead of 'sign', during the signature creation. 

I was also able to sign the pdf, however, none of my oids are working on the document's signature, resulting in a failure.
Expected result:
![Screenshot 2021-03-24 at 19 31 10](https://user-images.githubusercontent.com/8711911/112372444-b3f57f80-8cd7-11eb-892e-4f5f44ec0628.png)

Outcome:
![Screenshot 2021-03-24 at 19 31 27](https://user-images.githubusercontent.com/8711911/112372418-adff9e80-8cd7-11eb-9c79-9f2a61c5c9cd.png)

Can someone help, please?

**Comment by dhensby** [comment]
> I tried to use an x509 certificate to sign a pdf without the private key. Can you help with this challenge?

It is not possible to sign a document without a private key. What you're asking for is not possible.
