### ISSUE TITLE
[HELP]  property 'publicKey' of 'certBags[i].cert' is null.

### ISSUE THREAD

**Issue by amontero0611** [vbuch/node-signpdf#131]
Hi guys, I am stuck and would appreciate any help. I am getting the error above when trying to sign a document.
This is my code:
```
pdf.on('end', () => {
	console.log("pdfDoc.end");
	let pdfBuffer = Buffer.concat(pdfChunks);
	let signedPDF = signer.sign(pdfBuffer, 
				  fs.readFileSync('identity.p12'), 
				  additionalOptions = {passphrase: 'kk-kk'}); 
	fs.writeFileSync('document.pdf', signedPDF);
});

```
And the error follows:
**....\node_modules\node-signpdf\dist\signpdf.js:103
        publicKey
        ^
TypeError: Cannot destructure property 'publicKey' of 'certBags[i].cert' as it is null.**

Can someone please help figuring out what I am doing wrong?  Thank you in advance.

**Comment by amontero0611** [comment]
Got a possible answer: I am using ECDSA certificates (those provided by the Hyperledger Fabric CA) and they are not supported by node-forge.
Will seek for an alternative. Closing the issue.

**Comment by phidalgot** [comment]
@cw6365 @amontero0611  I have the same problem, could you find a solution?

**Comment by cw6365** [comment]
@phidalgot are you trying to sign with ECDSA keys? Node-forge only works with RSA keys. I had to fork forge and code this in to work with EC keys. I can share the code if this is the case.

**Comment by cw6365** [comment]
@phidalgot this is the PR i worked from https://github.com/digitalbazaar/forge/pull/925

**Comment by iqhuanhariirie** [comment]
> @phidalgot are you trying to sign with ECDSA keys? Node-forge only works with RSA keys. I had to fork forge and code this in to work with EC keys. I can share the code if this is the case.

can you share the code?
