### ISSUE TITLE
PAdES compliant signatures

### ISSUE THREAD

**Issue by Maxteke** [vbuch/node-signpdf#149]
Hello,

I'm trying to make a pades signature with your library.

```js
function sign(pdfName, p12Name, passphrase)
{
    let pdfBuffer = fs.readFileSync(__dirname + "/../ressources/" + pdfName);
    const p12Buffer = fs.readFileSync(__dirname + "/../ressources/" + p12Name);

    pdfBuffer = plainAddPlaceholder({
                pdfBuffer,
                signatureLength: p12Buffer.length,
                subFilter: SUBFILTER_ETSI_CADES_DETACHED,
            });
    
    try {
        const signedPdf = signer.sign(pdfBuffer, p12Buffer, {passphrase: passphrase});
        fs.writeFileSync(__dirname + "/../ressources/Signed_" + pdfName, signedPdf);
    } catch (e) {
        console.log(e.message);
    }
}
```
from this code the signature is invalid on dss platform:
![Capture](https://user-images.githubusercontent.com/46780628/140048827-004cea41-b71d-4076-8998-8c7ade648e85.PNG)

I tried to put the subFilter option on plainAddPlaceholder but the sub filter stay adbe.pkcs7.detached
https://github.com/vbuch/node-signpdf#pades-compliant-signatures

**Comment by vbuch** [comment]
Ah. I never got that released. In the repo you are looking at the docs of develop. Npm has what's in master. So... either wait for me to get a release out or use the develop code.

**Comment by vbuch** [comment]
This is out with 1.4.1 https://github.com/vbuch/node-signpdf/releases/tag/v1.4.0
Closing here.

**Comment by Maxteke** [comment]
Hi,

I retry with the latest version of your library.

The result change a little bit but stay invalid.
![image](https://user-images.githubusercontent.com/46780628/188645508-d180c9d1-e9fc-40c7-b43d-3a5e2589cf8c.png)
Thanks in advance for the help!
