### ISSUE TITLE
Help in designing the signature box

### ISSUE THREAD

**Issue by gaurav-cointab** [vbuch/node-signpdf#150]
Hi vbuch,

I have gone through a lot of your answers, and I have been able to go to the PR which was for pdfkit 0.11, and make the pdfkitAddPlaceholder work me, and finally the signature part also worked. Then I went through the answers and have made the changes so that the signature is visible in the page.

1If you could, also guide me to designing the signature box, so that we can finally use it. Currently I am getting a completely transparent box.

Can you please help me in this?

**Comment by vbuch** [comment]
Wow. Great. Now your head contains all the info I wish I had written somehwere in an FAQ format :-)
The last bit you need is not actually part of this package's purpose. You just want to add a graphic. Since yo are using pdfkit, I would suggest you do something in this manner: http://pdfkit.org/docs/vector.html
If you want raster: http://pdfkit.org/docs/images.html

**Comment by gaurav-cointab** [comment]
Hi vbuch,

Thanks for such a prompt reply, and sorry for being so late on checking back on this.

So the signature adding part, is basically done. Now what remains is the design, which is not a part of this lib.
So to sum up what you are suggesting is that we create the box, like we want to, so designing the signature box, like we want to, and just make it visible at the same co-ordinates the signature is (using the images, vectors, and other stuff from pdfkit). The design will be visible, and the signature will be just overlayed on top of it... right?

In this case we control the box design. We can make so that it is similar to the box which is generally display in adobe for other PDF. Am I understanding it correctly?

**Comment by vbuch** [comment]
Yes @gaurav-cointab. You design the visual as you wish and put the signature's clickable area on top.

**Comment by orlenkoo** [comment]
Hi @vbuch
Can share the sample code to create signature box with image&signature_info that can show the signature info by clicking it?

**Comment by prdufresne** [comment]
If I draw a signature box, can I put an empty signature's clickable area on top so that the user can sign it in Adobe?
