### ISSUE TITLE
How to verify digital signature signed by node-signpdf library . 

### ISSUE THREAD

**Issue by raheelLT** [vbuch/node-signpdf#156]

**Comment by vbuch** [comment]
- adobe acrobat reader
- libreoffice draw
- https://github.com/ninja-labs-tech/verify-pdf
- any other software that verifies pades

**Comment by raheelLT** [comment]
@vbuch Thanks for reply , am already using this lib to verify my digital signing, but the authenticity property for verifyPdf return false for me always . can you tell me what am doing wrong ?  plus am using the p12 certificate that you used in your library in the resources folder . can you tell exactly what am doing wrong here .

**Comment by FriendlyUser** [comment]
I also get the same error, verified is false, but I can still see my certificate in it.
