### ISSUE TITLE
Page format change after generate signature

### ISSUE THREAD

**Issue by cassiobt** [vbuch/node-signpdf#157]
I'm trying to generate a PDF with A5 format, but after sign de PDF it changes to A4 format with the content in A5, making a white space like in the image below:

![espaço em branco](https://user-images.githubusercontent.com/15292835/154973148-9a606717-d7e8-41da-ab78-7e0ef0432508.jpg)

**Comment by vbuch** [comment]
Just linking it as it is probably the same issue as #108 and #125

**Comment by cassiobt** [comment]
> Just linking it as it is probably the same issue as #108 and #125

Thank you for linking this similars issues. I think they can complement each other. 
As none of those issues are solved, I'll keep this opened.

**Comment by cassiobt** [comment]
I was using [https://github.com/marcbachmann/node-html-pdf](url) to generate the PDF. 
So I change to[https://github.com/mrafiqk/html-pdf-node](url) and now it works like a charm

**Comment by vbuch** [comment]
I'd say this is rather random. There are cases where we are losing metadata. I'd keep the issue open. Would be nice if you attach a failing file (generated with node-html-pdf)

**Comment by cassiobt** [comment]
@vbuch 
[issue-github-a5-a4.pdf](https://github.com/vbuch/node-signpdf/files/8132468/issue-github-a5-a4.pdf)

**Comment by vbuch** [comment]
@cassiobt you have provided an already broken file. Could you provide one befre you have tried to apply a signature/placeholder?

**Comment by cassiobt** [comment]
> 

Hi, 
Sorry about the delay. Here is the file before sign. 
[before-sign.pdf](https://github.com/vbuch/node-signpdf/files/8180641/before-sign.pdf)
