### ISSUE TITLE
After the signature is completed, the pdf data containing the signature page is lost

### ISSUE THREAD

**Issue by xakxak007** [vbuch/node-signpdf#158]
After signing with this test pdf, the black frame and part of the text on the first page will be lost.

"test.pdf" is before signature, "ok.pdf" is after signature👇

[test.pdf](https://github.com/vbuch/node-signpdf/files/8167008/test.pdf)
[ok.pdf](https://github.com/vbuch/node-signpdf/files/8167056/ok.pdf)

**Comment by vbuch** [comment]
![image](https://user-images.githubusercontent.com/5102057/161577061-83a91cf8-42fe-47ac-8c7d-9876451f9a8b.png)

Nice! I seem to have found and fixed it. Need to make sure it's all tested and there are no regressions, but it's promissing indeed.

**Comment by vbuch** [comment]
Fixed in 1.5.0
