### ISSUE TITLE
Adding a signature field for Adobe

### ISSUE THREAD

**Issue by Philip-Kazmeier** [vbuch/node-signpdf#164]
Hey guys,

I have a question regarding the usage of this library to create a signature field that can be used to digitally sign a PDF file.
In Adobe Pro I can create such fields (see here: https://helpx.adobe.com/sign/using/digital-signatures.html) in LaTeX i can use the `eforms` package for that (https://ctan.org/pkg/eforms).

I have already has a look at the addPlaceholder functionality (https://github.com/vbuch/node-signpdf/issues/159), but it seems like it is not like I would expect it. 

Is this even possible with the library?
If yes: How? Could anyone give an example on how to place the field on a certain page or on how to add multiple placeholders?
If no: Does anyone know an alternative? 

Greetings,
Philip

**Comment by prdufresne** [comment]
I'm certain there would be a great deal of demand for a response to this. I have been trying to work this out myself with no luck.

**Comment by vbuch** [comment]
#153 #150 #143 #129 #128 #107 #39 #26

**Comment by Philip-Kazmeier** [comment]
@vbuch So if I understand the referenced issues correctly, the purpose of this library is not to create such an element that can be used with Adobe. Is this assumption correct? Do you know of any other library that allows something like that?

**Comment by vbuch** [comment]
I really want to have the time to show you how this is done. I don't.

It won't be done with node-signpdf but rather with pdfkit, pdf-lib, etc.

**Comment by prdufresne** [comment]
It took my some time, because pdfkit doesn't have direct support for it, but I have figured out how to add the signature block using pdfkit. See the link below for the code I used. I basically manually add the signature field annotation. I also show how you could use it to lock fields when a signature is applied.

https://github.com/foliojs/pdfkit/issues/1381

**Comment by vbuch** [comment]
@prdufresne I just see your comment now. At the time you wrote it this was already demoed long ago in the tests. Hope the newly introduced examples will help more in the future. Here is a new one I'm adding. https://github.com/vbuch/node-signpdf/pull/200

**Comment by vbuch** [comment]
@Philip-Kazmeier you are right. The initial idea of node-signpdf was to only provide the cryptgraphic part of the signing which is something Adobe will do in your use-case. Now this has changed quite recently and that part of node-signpdf is now called @signpdf/signpdf. The parts reagarding your needs are separate packages. Currently https://www.npmjs.com/package/@signpdf/placeholder-pdfkit010 and https://www.npmjs.com/package/@signpdf/placeholder-plain are available. Hopefully me or other contributors will create more of these.
