### ISSUE TITLE
Demo of flow ?

### ISSUE THREAD

**Issue by jesperordrup** [vbuch/node-signpdf#165]
Are there a demo of this somewhere? I've read through the description and I'm still (sorry) in doubt of how this package/code helps, where it starts and ends.

My usecase 
On a website we have an apply for employment flow with a form.
We have a pdf. It's probably a generic contract pdf. We want to have this signed and uploaded as a part of this process.
When I say sign, I mean "add your scrippled signature".
We are not needing a verification of ident (digital sign), just a "e-signature".

Can you tell me how much of the above this package does?

Thank you.

**Comment by vbuch** [comment]
The library only works with digital signatures (verifiable, PAdES) and not with the visual part.
