### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Raimundo82** [vbuch/node-signpdf#170]
HI,

I am not sure if i can consider the following a issue, but as far as i can see, this package is not supported on browser environment.

Since the original application, pdfsigned.js ran on the client, it is expected that a client-side version will be developed ?

**Comment by vbuch** [comment]
Sorry. I personally don't have any plans on the topic. Theretically, when I rework the code for 2.0, this may come as a feature. But that's not a promise as I've been trying to find time for that rework for more than a year.
