### ISSUE TITLE
PDF signature with pkcs#7 format certificate

### ISSUE THREAD

**Issue by Faystos** [vbuch/node-signpdf#173]
Hello, there are problems when using the library to sign a PDF file with a pkcs#7 usb token format certificate, an error occurs:
"(node:21785) UnhandledPromiseRejectionWarning: Error: Unparsed DER bytes remain after ASN.1 parsing."

The question arises whether this library can be signed with a pkcs#7 format certificate?
There is no mention in the documentation, if there is a wild excuse, could you then throw off the section where there are mentions

**Comment by ParitoshKarnatak** [comment]
Is there any solution on this for signing a pdf using pkcs7 in nodejs?
