### ISSUE TITLE
invalid asymmetric cipher when pdf has metadata

### ISSUE THREAD

**Issue by felipeduarte27** [vbuch/node-signpdf#176]
I'm facing a problem that is when signing a pdf that contains metadata the asymmetric cipher is invalid.

If anyone can help me, I'd appreciate it!

**Comment by ph-gomes** [comment]
I'm facing the same issue, do you have any progress?

**Comment by felipeduarte27** [comment]
unfortunately not

**Comment by ph-gomes** [comment]
Hi there, I've created a PR at pdf-signer to fix a related issue, you can check that at: https://github.com/vizicsaba89/pdf-signer/pull/48
