### ISSUE TITLE
Two signatures

### ISSUE THREAD

**Issue by alvinmandala** [vbuch/node-signpdf#18]
Thank you so much for this awesome library. I would like to ask whether there is a way to put two signatures directly in one go.

**Comment by vbuch** [comment]
You asked it and then closed it. Either way: to my understanding two larties cannot simultaneously sign a documents. Like in paper documents. One party signs and then handles the documents to the other party already signed so they apply their signatures as well. This is doable as per the pdf specs but I do not have an example of it. It cannot happen with pdfkit AFAIK. So you can try and implement incremental update yourself. It is not rocket science. See here for tips https://blog.idrsolutions.com/2013/06/how-to-edit-pdf-files/

**Comment by vbuch** [comment]
Just to confirm my previous comment:
Here are the specs of PAdES defined by ETSI: https://www.etsi.org/deliver/etsi_ts/102700_102799/10277801/01.01.01_60/ts_10277801v010101p.pdf
See section 4.4
