### ISSUE TITLE
Upgrade pdfkit version

### ISSUE THREAD

**Issue by bhelzer** [vbuch/node-signpdf#207]
**Describe the bug and the expected behaviour**
Please upgrade the peerDependency to the newest pdfkit version (0.14.0)

**Is it a bug in signing or in the helpers?**
In the helper library placeholder-pdfkit010

**To Reproduce**
I realize the library is called placeholder-pdfkit010, and maybe it should be renamed. However upgrading the version to 0.14.0, and keeping it up-to-date would be very useful.

**Comment by vbuch** [comment]
Hi @bhelzer ,
Thank you for this.

Having an up-to-date placeholder helper with pdfkit is something that needs to happen. My plan is to create a separate one - placeholder-pdfkit and keep it up with the peer dep. This would deprecate the 010 one. The main problem with just upgrading is that placeholder-plain is based and uses 010. A separate package dodges this.

As always: my time is limited but PRs are welcome.

**Comment by vbuch** [comment]
@dhensby already did some of the related work in https://github.com/vbuch/node-signpdf/pull/115 for 0.11. 0.14 is a lot later so maybe there's more to it.

**Comment by dhensby** [comment]
It was an absolute pain to try to get 0.11 support working properly because it had added form support and (IIRC - it was ages ago) it caused all sorts of internal issues.

PS: @vbuch - do you have a way we can chat (gitter/slack/etc), just so we can chat about how contributions would be best planned/focused?

**Comment by vbuch** [comment]
@dhensby yes. That's why I want it to be separate and not an upgrade of the current one.

PS: Msged you on LinkedIn

**Comment by vbuch** [comment]
@bhelzer, see https://github.com/vbuch/node-signpdf/releases/tag/placeholder-pdfkit-3.1.0
This is @dhensby 's work being released as `placeholder-pdfkit` that is compatible with PDFKit versions 0.11 and above.
