### ISSUE TITLE
How-to Sign already create PDF document

### ISSUE THREAD

**Issue by moshebeeri** [vbuch/node-signpdf#22]
Hi Guys,

Grate work...
I'll will appreciate to create and submit a demo of using node-signpdf for the ones using jsPDF.
The problem is that I can not find how to create the placeholders as shows on the [tests](https://github.com/vbuch/node-signpdf/blob/master/src/helpers.js#L12)

`    
    const signature = pdf.ref({
        Type: 'Sig',
        Filter: 'Adobe.PPKLite',
        SubFilter: 'adbe.pkcs7.detached',
        ByteRange: [
            0,
            DEFAULT_BYTE_RANGE_PLACEHOLDER,
            DEFAULT_BYTE_RANGE_PLACEHOLDER,
            DEFAULT_BYTE_RANGE_PLACEHOLDER,
        ],
        Contents: Buffer.from(String.fromCharCode(0).repeat(signatureLength)),
        Reason: new String(reason), // eslint-disable-line no-new-wrappers
        M: new Date(),
    });
`
When looking on the jsPDF I could not find the equivalent to pdf.ref, but I am sure there is a way to do that, any idea?

**Comment by vbuch** [comment]
Heads up: What the ref function basically does in pdfkit is store an item an enumerate it. So just reading the trailer will give you the current number of items. Use that number for you next added item and increase the number in the trailer. Link the AcroForm in the root descriptor. That's all you need to do.

**Comment by vbuch** [comment]
I've started playing with this a bit: https://github.com/vbuch/node-signpdf/tree/play-with-trailers
It's hell lot of string/buffer operations that need to be done, but seems like it is doable at least to the bare minimum functionality. Will let you know once I have something working.

**Comment by vbuch** [comment]
@moshebeeri could you give this peace of code a try?

https://github.com/vbuch/node-signpdf/blob/play-with-trailers/src/signpdf.test.js#L132

It does work following the happiest path possible.

**Comment by moshebeeri** [comment]
@vbuch You are the best !!!
Thanks, I'm back from Passover vacation, I'll give it a try.
You'r solution is indeed generalized for all generated externally pdf's, therefor I am changing this post title to reflect the issue for other who may seek a way to do that.
I'll keep you posted.

**Comment by vbuch** [comment]
Why did you close it, @moshebeeri? Does it work? It's still in a branch and unofficial. Ill keep the issue open until this is released.

**Comment by vbuch** [comment]
This is out with 1.0.0

**Comment by aronmoles** [comment]
This method deletes the metadata from the file. 
Would it be possible to maintain these metadata?

Thanks

**Comment by aronmoles** [comment]
Can you help me @vbuch?

Thanks

**Comment by vbuch** [comment]
Ive missed that previous comment. Sorry @aronmoles
This is a closed issue. Create a new one please and provide example pdf so I can see where there is an issue.

**Comment by inane** [comment]
Hello, is it possible to update again this link? https://github.com/vbuch/node-signpdf/issues/22#issuecomment-485344073

I am trying to sign and add  a plain placeholder but it is not being possible. Sign is correct but not plain placeholder. Any clue or help @vbuch ? Thank you in advance.

**Comment by vbuch** [comment]
No. Not much, @inane This comment was pointing to the branch where plainAddPlaceholder was initially created. It has evolved since. A good hint for you would be that it only works for PDF versions <= 1.3. I think noone reported issues with those so far. On the other hand there are lots of issues with PDF > 1.3. So... if you have a 1.3 pdf, you could use the plainAddPlaceholder. If you have a >1.3, we will all appreciate a PR that know how to do the magic.

**Comment by inane** [comment]
I have used a web converter to downgrade my pdf document to 1.3 version and result is the same. :-(

**Comment by vbuch** [comment]
No. That was some work in progress. The code has evolved since then. The linked code is in some form in our dev and master branches at the moment. I don't understand how signature is correct but placeholder isn't. Please open a new issue and provide examples if you want someone to take a look at your issue. This one is closed. Here are [some tests that demonstrate plainAddPlaceholder](https://github.com/vbuch/node-signpdf/blob/develop/src/signpdf.test.js#L147)

**Comment by inane** [comment]
Thank you for your last response. I was reading link about plainAddPlaceHolder and I added this code in the function:

```
async function signDocument ( req, res ) {
  const passphrase = 'DA5cJvezM6Px6JLR',
        p12Buffer  = fs.readFileSync ( `${ __dirname }/WktYaXJlM1VOY0RxdG1kQw==.p12` ),
        payload    = {
          documento : req.file.path
        }
  let pdfBuffer    = fs.readFileSync ( req.file.path )

  pdfBuffer = helpers.plainAddPlaceholder ( {
    pdfBuffer,
    reason: 'TESTING',
    signatureLength: 15544,
  } )
  pdfBuffer = signer.default.sign ( pdfBuffer, p12Buffer, { passphrase } )

  fs.writeFileSync ( `${ __dirname }/` + req.file.originalname, pdfBuffer )
  await models.Firma.create ( payload )
  response.successResponse ( req, res, req.body, 'DOCUMENT_SIGNED_SUCCESSFUL' )
}

```

Are you seeing something wrong?
