### ISSUE TITLE
Can't deploy on mongo.db using mexc-sdk js

### ISSUE THREAD

**Issue by CristiCh** [vbuch/node-signpdf#255]
Hello

I want to know why I get the following error: failed to execute source for ‘node_modules/mexc-api-sdk/src/index.js’: FunctionError: failed to execute source for ‘node_modules/mexc-api-sdk/src/modules/index.js’

Can anyone help pls?
Thank you!

**Comment by vbuch** [comment]
Sorry. No clue what mexc-api-sdk is and how it relates to signpdf.
