### ISSUE TITLE
How-to make signature visible on PDF

### ISSUE THREAD

**Issue by vidigas** [vbuch/node-signpdf#26]
Hi there, 

thanks a lot for the lib.

I have implemented de signature with . a p12 file on the pdf and I am being able to check the signature on the available validation tools, but the signature is no visible on pdf itself when open on regular pdf viewer.

Is it possible to do so?
Let a visible mark that the document has being signed.

Thanks

**Comment by vbuch** [comment]
You can add some "drawing" or text to the document to state that. You can also make the Widget visible. But it won't be clickable in e.g. Chrome. Only in Adobe's products (and probably others who have implementation of pdf signature verification). I hope I'll be able to demonstrate drawing a signature with PdfKit in version 1+. Wont happen for 1.0. And not sure if i'll be able to do it with non-pdfkit code.

**Comment by vidigas** [comment]
Sorry for the silly question, but how to make the widget visible?
First time dealing with pdf's.  I'm heaving a bit of a hard time here...

**Comment by vbuch** [comment]
To make the widget clickable (in Adobe Reader), you need to set a non-zero rect here: https://github.com/vbuch/node-signpdf/blob/develop/src/helpers.js#L35
This will just add some dot-bordered rectangle that is clickable and opens the signatures panel.
If you add some text to the same place like "This document is digitally signed" it will llook like you are clicking the text. Those are two totally separate things. Imagine the clickable element being absolutely positioned on top of the text.

**Comment by arpitsr91** [comment]
@vbuch Hi Valery. Sorry to bump this, but I put a non-zero rect while creating the widget as per your suggestion, to get a clickable area, but it doesn't seem to work for me. Or maybe I'm understanding this wrong. Can you please let me know where and how to update my code to get it working? FYI, the link in your above comment does'nt exist anymore.

**Comment by PedroS11** [comment]
I tried to set Rect to non-zero however it doesn't show any widget. Can you give a sample code or some help? Because we can't see the dot-bordered rectangle

**Comment by jackeyWanFei** [comment]
@vbuch  I solved it in My vue project yestoday.

**Comment by jackeyWanFei** [comment]
But not used in node. I used pdfsign.js library

**Comment by hmpvillegas** [comment]
> But not used in node. I used pdfsign.js library

can you post and explain it here? thanks

**Comment by jackeyWanFei** [comment]
> > But not used in node. I used pdfsign.js library
> 
> can you post and explain it here? thanks

I'll push it out next few days

**Comment by jackeyWanFei** [comment]
> > But not used in node. I used pdfsign.js library
> 
> can you post and explain it here? thanks

[https://github.com/jackeyWanFei/vue-signPdfWithStamper](url)
my project

**Comment by jackeyWanFei** [comment]
> > But not used in node. I used pdfsign.js library
> 
> can you post and explain it here? thanks

[my project](https://github.com/jackeyWanFei/vue-signPdfWithStamper)

**Comment by lucasmassi** [comment]
This lib is top for your issue https://github.com/chunyenHuang/hummusRecipe

**Comment by lucasmassi** [comment]
Only save one copy of your PDF and use the new with visible signature to be signed.

**Comment by nparween** [comment]
I want a sample code to make the signature visible in existing PDF.

**Comment by PinkFLoyd92** [comment]
Have you found any solution in order to show the signature? I can't make it visible with this library.

**Comment by lucasmassi** [comment]
Yes, i modified this lib, but I don't remember what I touched specifically.

Em dom., 13 de set. de 2020 às 17:56, Sebastián Cáceres <
notifications@github.com> escreveu:

**Comment by amitraky** [comment]
> non-pdfkit

are you implement it without pdfkit
