### ISSUE TITLE
PNG Signature Images - Question

### ISSUE THREAD

**Issue by mcarpenterjr** [vbuch/node-signpdf#262]
I have a use case where a PDF is being created by contributors that needs to be signed, I have PNGs of each contributor's signature, and each contributor has a certificate. Does signpdf support using an image of a signature instead of a place holder?

**Comment by vbuch** [comment]
The library does the crypto part of e-signature. The visuals you need to handle through something else - something lik pdf-lib

**Comment by mcarpenterjr** [comment]
Awesome, thank you.

**Comment by aditya9783** [comment]
How the handle Visuals ? is there any example for that

**Comment by vbuch** [comment]
@aditya9783 here is one example: https://github.com/vbuch/node-signpdf/blob/develop/packages/examples/src/pdfkit010-with-visual.js#L81

**Comment by aditya9783** [comment]
@vbuch Thanks for the example reference. But as I read about pdfkit010 , it created new pdf it doesn't modify existing pdf,
in my case i am receiving PDF from another source in my node.js api and using signpdf, pdf-lib , it is successfully signed ,and placeholder is also added  . But there blank rectangle box . Nothing is visually appearing.

**like that**.
<img width="807" height="567" alt="Image" src="https://github.com/user-attachments/assets/95ed2fb7-330c-425d-8c71-49e0ebc9e791" /> 

**but i want to display like this**  . I want to show like this 

<img width="665" height="494" alt="Image" src="https://github.com/user-attachments/assets/4fbb9cc9-e4da-48d9-a381-82a13f468b4a" />

 Please guide me , please tell me where i am doing wrong . Please guide Acc. to my requirement.

I am opening those PDF's in same Adobe Acrobat

**Comment by vbuch** [comment]
@aditya9783 , Drawing on the pdf is something you would achieve with pdf-lib. And if you look at the example you'll see what needs to happen:
* you first draw on the page (visual signature)
* you then apply a pdf signature (cryptographic one)

and you make sure these two are placed at the same place
