### ISSUE TITLE
multiple signature using placeholder-pdf-lib and pdfkitAddPlaceholders packages

### ISSUE THREAD

**Issue by Gladstone-Thiago** [vbuch/node-signpdf#278]
Description: When adding a second signature, the pdfkitAddPlaceholders package in the const const isAcroFormExists = typeof pdf._root.data.AcroForm !== "undefined"; becomes undefined, not finding the AcroForm and consequently leaving the fieldIds empty. 
![Uploading Screenshot 2024-11-26 at 18.55.52.png…]()
How to reproduce: just try to sign the attached PDF and the bug can be reproduced.
[pdf-to-signer_assinado.pdf](https://github.com/user-attachments/files/17926170/pdf-to-signer_assinado.pdf)
[pdf.txt](https://github.com/user-attachments/files/17926171/pdf.txt)

**Comment by Milad305** [comment]
try to use plainaddplacholder (placeholder-plain) instead of pdfkitAddPlaceholders

**Comment by vbuch** [comment]
pdfkit won't let you work incrementally. plain is the tool that comes in here. Note that plain doesn't understand streams so you may need adjustments when saving the document with pdfkit.
