### ISSUE TITLE
planAddPlaceholder problem with steam xref (compressed Pdf)

### ISSUE THREAD

**Issue by Milad305** [vbuch/node-signpdf#279]
when i want to sign a pdf with planAddPlaceholder (because i need multi sign) that is compressed it cant read the xref table 
45 0 obj
<</Length 68/Filter/FlateDecode/Size 46/Root 3 0 R/Info 2 0 R/W[1 3 2]/Type/XRef/Index[0 1 2 2 12 1 35 11]/Prev 295632>>stream
x�c```�����r#�5&-fF��~���6y!	D6��"�&BU�t݅��$� �	 "��
endstream
endobj

this was the pdfs xref in compressed way .do you guys have any idea ?

**Comment by vbuch** [comment]
plainAddPlaceholder doesn't understand streams. It's rather... 'plain'. Sorry.
