### ISSUE TITLE
Adobe Parameter Error After Sign

### ISSUE THREAD

**Issue by samuelb97** [vbuch/node-signpdf#31]
I have ported the code to work with express. 
Steps
1) Add Placeholder to PDF Buffer
2)  Get Sign Header
3) Use Forge to sign with p12 file saved in root folder
4) Use fs.writefilesync to write the buffer with signature to a new pdf file

The created pdf file opens with the content. It shows a signature on the document but Adobe says its invalid, when trying to validate it I get 
"""
Error during signature verification.  

Adobe Acrobat error.
Bad parameter.
"""

I'm using plainAddPlaceholder to add the placeholder.
I am trying to get it to work with already created pdf files.

**Comment by vbuch** [comment]
Can you give a copy of the raw pdf? The not-yet-signed one? There shouldnt be an issue with express. The lib just takes a pdf. Doesnt carebwhere it came from. Actually the initial use-case I had we had was an api call to create the document and sign it. It should work at least for basic non-revisioned pdfs.

**Comment by vbuch** [comment]
Outdated. Closing.
