### ISSUE TITLE
Error: A PDF file must end with an EOF line.

### ISSUE THREAD

**Issue by iopazo** [vbuch/node-signpdf#35]
I had some problems when reading the pdf file from the buffer, since once called the function .sign (), this throws the following error:

```
/Users/iopazo/Develop/uno/transmision-api/node_modules/node-signpdf/dist/helpers/removeTrailingNewLine.js:40
     throw new _SignPdfError.default (
     ^

Error: A PDF file must end with an EOF line.
```

Imagine the problem was with one of my PDF files, but checking these if they have the final line.

Here is my integration:

```
    const signer = require('node-signpdf').default;

    let pdfBuffer = fs.readFileSync(file);

    const signedPdf = signer.sign(pdfBuffer, fs.readFileSync(signature));
    console.log(signedPdf);
```
[comprobante_incorporacion.pdf](https://github.com/vbuch/node-signpdf/files/3643048/comprobante_incorporacion.pdf)

From already thank you very much!

**Comment by vbuch** [comment]
Here is the code that gives you an error: https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/removeTrailingNewLine.js#L18

I am on mobile and with only a text editpr available I see this: http://imgur.com/gallery/dapeKIz
This looks like an unexpected symbol at the end of the document but i am not sure what it is and if it is valid in PDF1.7. Need to research that when I have access to a computer.

**Comment by vbuch** [comment]
Yup. Now on a desktop I see it has a NUL byte at the end: https://imgur.com/gallery/0w9fNth
Let me track what the spec has to say on that.

**Comment by vbuch** [comment]
OK. So the first finding is a bug. The specs say in section 7.5.1 that lines may end with `\r`, `\n` or both. This needs to be fixed when removing the last character.
It also says "the last line shall contain only the EOF marker.". Considering that all lines end with `\r`, `\n` or both, I would say that the null byte at the end of this file makes it invalid, though the viewers tend to ignore it. I would not go for trimming the end of the file for this specific case. As per the spec, it is an invalid ending of the file.

**Comment by PedroS11** [comment]
So how should I solve this problem ? All my pdf's have that null byte in the end and I can't trim a buffer.

**Comment by vbuch** [comment]
If I was doing this for my PDFs I would go, get the last char and check it explicitly. If it is the one, I would feed the signer with a buffer that doesn't have it. This is: I would do it out of the library to keep the library closer to the specs.

**Comment by vbuch** [comment]
I think there is not much to add here, unless this is really an issue with the lib which I think is not the case. Closing.

**Comment by manashee** [comment]
Dear Valery ,
Any luck with fixing the issue:
  The lines may end with \r, \n or both?

 I have many pdfs ( generated from magento ) which have only \r before %%EOF. (There is no Null charecter after EOF)
 and node-signpdf produces the above error "Error: A PDF file must end with an EOF line."

**Comment by vbuch** [comment]
https://github.com/vbuch/node-signpdf/blob/83c7abcb31815b774a84cf910b258a7be1236945/src/helpers/removeTrailingNewLine.js#L32

Noone has fixed that, so... PRs welcome.

**Comment by romulotorres** [comment]
I'm facing this error too. Something news about fix that?

**Comment by ValZapod** [comment]
This 0x00 is added by some dumb network app. See this for example: https://doc.lagout.org/science/0_Computer%20Science/3_Theory/Mathematics/Exploring%20Abstract%20Algebra%20with%20Mathematica%20%5BHibbard%20%26%20Levasseur%201999-02-19%5D.pdf

the file has 0x00 in the end and yet otherwise bitperfect file from libgen does not have it! WTF. https://libgen.li/edition.php?id=139704336

As for 0D 0A I suppose the standard is vague enough. 
>Considering that all lines end with \r, \n or both

That is wrong. Last line ends with nothing. If it ends with those, there is now a new line. But here the pdfs created by Acrobat are the reference, both docx printed to pdf and .ps files to pdf by Distiller end in 0D 0A.

**Comment by materazu** [comment]
Same here, with pdf exported via google doc export
