### ISSUE TITLE
function plainAddPlaceholder remove metadata of pdf

### ISSUE THREAD

**Issue by aronmoles** [vbuch/node-signpdf#36]
Hi.

I'm using a function plainAddPlaceholder to sign pdf with metadata. Library sign correctly a file, but remove all metadata of his.

This is my code:

```
const pdfBuffer = fs.readFileSync(absoluteLocalPath);
const signBuffer = fs.readFileSync(process.env.CERTIFICATE_PATH);
let inputBuffer = plainAddPlaceholder({
      pdfBuffer,
      reason: 'I have reviewed it.',
      signatureLength: signBuffer.length,
});

const signedPdf = signer.sign(
      inputBuffer,
     signBuffer,
     { passphrase: 'badssl.com' },
);

fs.writeFileSync(absoluteLocalPath, signedPdf);
```

Can you help me @vbuch?

Thanks

Regards.`

**Comment by vbuch** [comment]
Sorry. Just seeing this now @aronmoles Can you give me an example PDF file that is getting broken. I'm guessing we're overwriting some link somewhere so the metadata is probably remaining in the PDF but we're unlinking it. Please, give me a sample document.

**Comment by vbuch** [comment]
`plainAddPlaceholder` was pretty much rewritten. I would guess that the reported issue no longer exists. Closing the issue. If, however, there is a good report with test data, feel free to comment and we will reopen it. Or create a new one.
