### ISSUE TITLE
confused arguments

### ISSUE THREAD

**Issue by alekssakovsky** [vbuch/node-signpdf#4]
import signer from 'node-signpdf';
 
const signedPdf = signer.sign(
  fs.readFileSync(PATH_TO_P12_CERTIFICATE),
  fs.readFileSync(PATH_TO_PDF_FILE)
); <<<<<<<- in manual

sign(pdfBuffer, p12Buffer) { <<<<<<<<- in code

**Comment by vbuch** [comment]
Resolved with https://github.com/vbuch/node-signpdf/pull/6
