### ISSUE TITLE
Signing with pkcs11

### ISSUE THREAD

**Issue by andres-blanco** [vbuch/node-signpdf#40]
Hey, I have a branch working with pkcs11 tokens. It's still a WIP but it works. The relevant code is here: https://github.com/SIU-Toba/node-signpdf/blob/feature/pkcs11-token/src/signpdf.js#L137

The problem I have is that the token needs the raw byte buffer to digest and sign. The node-forge lib sends a message digest object as parameter, so I don't have access to the raw bytes.
I created this issue in node-forge https://github.com/digitalbazaar/forge/issues/729

Does anybody here knows how can I obtain the raw signable buffer from the message digest sent by node-forge? This is important if you want to use signed attributes.

**Comment by vbuch** [comment]
Just commented on your issue in forge. Also take a look at what I've written here https://github.com/vbuch/node-signpdf/issues/32#issuecomment-530269128

**Comment by andres-blanco** [comment]
Hey, i found the correct way to sign the pdf content, you can see [this answer](https://github.com/digitalbazaar/forge/issues/729#issuecomment-554425018).

@vbuch how do you suggest to test this? There is [this library](https://github.com/opendnssec/SoftHSMv2) that emulates a hardware token, do you think I should include this lib in the resources dir?

**Comment by vbuch** [comment]
Great!
I wouldnt include a whole library for automated testing. I would makenit work for me (with a hardware token or with an emulater software one as proposed) and once I have the flow satisfactory for me, I would mock the library and hardcode stubs. But this is me. If you have a better approach, it wohld be welcome.

**Comment by wil512on** [comment]
hi @andres-blanco  
Do you have any idea how to use your example with fortify app to return the signature. thanks, I used it with graphene and it worked great.


 I have this with fortify, but the signature in invalid in the pdf:

var provider = await ws.getCrypto($$('providers').getValue())
var signer = {}
        signer.sign = await new Promise(resolve => {
          resolve(async (md, algo) => {
            // https://stackoverflow.com/a/47106124
            var prefix = Buffer.from([
              0x30, 0x31, 0x30, 0x0d,
              0x06, 0x09, 0x60, 0x86,
              0x48, 0x01, 0x65, 0x03,
              0x04, 0x02, 0x01, 0x05,
              0x00, 0x04, 0x20
            ])
            var buf = Buffer.concat([prefix, Buffer.from(md.digest().toHex(), 'hex')])

            var sigmd = await provider.subtle.sign('RSASSA-PKCS1-V1_5', key, buf)
            var pvt = pvtsutils.Convert.ToBinary(sigmd)
            return pvt
            // return Buffer.from(sigmd).toString('binary') // sigmd.toString('binary')
          })
        })

links example fortify 
https://github.com/PeculiarVentures/fortify-examples/blob/gh-pages/example5.html
https://peculiarventures.github.io/fortify-examples/example5.html

thanks.!

**Comment by andres-blanco** [comment]
It's hard to know for me since I am not familiar with fortify. One thing you could try is seeing if avoiding the prefix works.
For what is worth, I used this tool to inspect the signature asn1 package: https://lapo.it/asn1js/
I also used https://mupdf.com/index.html (mutool sign) to verify the signatures in the command line in linux.
sorry that I cannot help further

**Comment by nguyenbinhdai** [comment]
const graphene = require("graphene-pk11")
const Module = graphene.Module
const forge = require("node-forge")
const pki = forge.pki
const HELPERS = require("node-signpdf/dist/helpers")
const DEFAULT_BYTE_RANGE_PLACEHOLDER = "**********"
let mod,session
mod = Module.load("pvpkcs11.dll")
mod.initialize()
const slots = mod.getSlots()
const slot = slots.items(0)
const initialized = (slot.flags & graphene.SlotFlag.TOKEN_PRESENT)
if (!initialized) throw new Error("Slot 0 is not initialized")
session = slot.open()

const getPkById=(id) => {
    const keys = session.find({ class: graphene.ObjectClass.PRIVATE_KEY })
    for (let i = 0; i < keys.length; i++) {
        const obj = keys.items(i).toType()
        if (id === obj.id.toString("hex")) return obj
    }
    return null
}

const getCertAndPk=() => {
    const certs = session.find({ class: graphene.ObjectClass.CERTIFICATE })
    for (let i = 0; i < certs.length; i++) {
        const obj = certs.items(i).toType()
        if (obj instanceof graphene.X509Certificate) {
            const val = obj.value, cert = pki.certificateFromAsn1(forge.asn1.fromDer(val.toString("binary")))
            const id = obj.id.toString("hex"), privateKey = getPkById(id)
            return { privateKey: privateKey, certificate: cert } 
        }
    }
    return { privateKey: null, certificate: null }
}

const signpdf = (pdfBuffer) => {
    	const { privateKey, certificate } = getCertAndPk()
		if (!certificate) throw new Error("certificate is not found")
        if (!privateKey) throw new Error("privateKey is not found")
		pdfBuffer = HELPERS.plainAddPlaceholder({ pdfBuffer, reason: 'reason' })
        let pdf = HELPERS.removeTrailingNewLine(pdfBuffer)
        const byteRangePlaceholder = [0, `/${DEFAULT_BYTE_RANGE_PLACEHOLDER}`, `/${DEFAULT_BYTE_RANGE_PLACEHOLDER}`, `/${DEFAULT_BYTE_RANGE_PLACEHOLDER}`]
        const byteRangeString = `/ByteRange [${byteRangePlaceholder.join(' ')}]`
        const byteRangePos = pdf.indexOf(byteRangeString)
        if (byteRangePos === -1) throw new Error(`Could not find ByteRange placeholder: ${byteRangeString}`)
        const byteRangeEnd = byteRangePos + byteRangeString.length
        const contentsTagPos = pdf.indexOf('/Contents ', byteRangeEnd)
        const placeholderPos = pdf.indexOf('<', contentsTagPos)
        const placeholderEnd = pdf.indexOf('>', placeholderPos)
        const placeholderLengthWithBrackets = (placeholderEnd + 1) - placeholderPos
        const placeholderLength = placeholderLengthWithBrackets - 2
        const byteRange = [0, 0, 0, 0]
        byteRange[1] = placeholderPos
        byteRange[2] = byteRange[1] + placeholderLengthWithBrackets
        byteRange[3] = pdf.length - byteRange[2]
        let actualByteRange = `/ByteRange [${byteRange.join(' ')}]`
        actualByteRange += ' '.repeat(byteRangeString.length - actualByteRange.length)
        pdf = Buffer.concat([pdf.slice(0, byteRangePos), Buffer.from(actualByteRange), pdf.slice(byteRangeEnd)])
        pdf = Buffer.concat([pdf.slice(0, byteRange[1]), pdf.slice(byteRange[2], byteRange[2] + byteRange[3])])
        const sign = session.createSign("SHA256_RSA_PKCS", privateKey)
        const sigv = sign.once(pdf).toString("binary")
        const p7 = forge.pkcs7.createSignedData()
        p7.content = forge.util.createBuffer(pdf.toString("binary"))
        p7.addCertificate(certificate)
        const signer = {}
        signer.sign = (md, algo) => { return sigv }
        p7.addSigner({ key: signer, certificate: certificate, digestAlgorithm: pki.oids.sha256 })
        p7.sign({ detached: true })
        const raw = forge.asn1.toDer(p7.toAsn1()).getBytes()
        if ((raw.length * 2) > placeholderLength) throw new Error(`Signature exceeds placeholder length: ${raw.length * 2} > ${placeholderLength}`)
        let signature = Buffer.from(raw, "binary").toString("hex")
        signature += Buffer.from(String.fromCharCode(0).repeat((placeholderLength / 2) - raw.length)).toString("hex")
        pdf = Buffer.concat([pdf.slice(0, byteRange[1]), Buffer.from(`<${signature}>`), pdf.slice(byteRange[1])])
        return pdf
}

**Comment by nguyenbinhdai** [comment]
[pkcs11.zip](https://github.com/vbuch/node-signpdf/files/4567483/pkcs11.zip)

**Comment by nguyenbinhdai** [comment]
My example above can signing pdf . I using node-signpdf, graphene-pk11, pvpkcs11.

**Comment by chayakornjj** [comment]
@andres-blanco Hi Andres, Sorry for wake up this one. I'm also found the issue to use this with PKCS#11 (With HSM) Any recommendation for me to use this for digital signature (Signing PDF).

**Comment by andres-blanco** [comment]
> @andres-blanco Hi Andres, Sorry for wake up this one. I'm also found the issue to use this with PKCS#11 (With HSM) Any recommendation for me to use this for digital signature (Signing PDF).

I made some tests with bittersweet results. I managed to add the digital signature to a pdf and it checked out in adobe pdf reader. When I tried using a signature that was signed with a CA I couldn't do it, the signature was always corrupted. In the end I didn't use it. If you want you can see the code here: https://github.com/SIU-Toba/node-signpdf/tree/feature/pkcs11-token
I ended up using pdfbox for java because it's a really mature pdf library

**Comment by rossinicolas** [comment]
> > @andres-blanco Hi Andres, Sorry for wake up this one. I'm also found the issue to use this with PKCS#11 (With HSM) Any recommendation for me to use this for digital signature (Signing PDF).
> 
> I made some tests with bittersweet results. I managed to add the digital signature to a pdf and it checked out in adobe pdf reader. When I tried using a signature that was signed with a CA I couldn't do it, the signature was always corrupted. In the end I didn't use it. If you want you can see the code here: https://github.com/SIU-Toba/node-signpdf/tree/feature/pkcs11-token
> I ended up using pdfbox for java because it's a really mature pdf library

@andres-blanco buenos días, tambien estoy buscando una solución para generar y firmar PDFs mediante la lectura de certificados desde una aplicación web NextJS que se conecta al cliente Fortify Local. Me comentas si tenias un problema similiar y de  ser asi como lo resolviste. Gracias.

**Comment by cmjunior** [comment]
> 

@wil512on did you found out how to adapt this example to use Fortify? I'm not sure how to generate a forge.asn1 from the certificates returned by Fortify.
