### ISSUE TITLE
TypeScript version

### ISSUE THREAD

**Issue by moravcik** [vbuch/node-signpdf#45]
First of all, thank you for your awesome work, it is really far from trivial to implement the signing of PDFs in pure node. Great job.

In our team we are writing all the JavaScript code in TypeScript, so it is better manageable, better understandable and less error-prone and I was quite missing the type safety it in the `node-signpdf`. So I have stopped a little bit to migrate all the code to TypeScript (including tests). I was not able to back-engineer all the types used, so in few edge cases I have used magical keyword `any`.

All `package.json` scripts work, all tests pass, everything seems to be ok.
If you are interested I can send you PR.

**Comment by vbuch** [comment]
I generally like TS but never start something from scratch with it dute to som quircks it has. Would love to see the code, written in TS. Can't promise It'll go live. I would prefer to keep it more readable and... keeping it as vinalla as possible is something that helps in that direction. Definitions on the other hand would be very welcome. So... going the other way around. Instead of writing it in TS and downgrading for everyone I prefer writing it vanillish and enriching with TS desfinitions, flow, etc.
Let me see what you have there thou. Might be helpful for people.

**Comment by moravcik** [comment]
Thank you for your reply. I did minimal changes to the code - just renaming files from `*.js` to `*.ts` and mostly only adding types - to improve readability. I have made none structural or functional changes to the code, so all the usage remains the same - you just see what functions do expect and what is the result.
Only thing to mention, I have just replaced most of default exports to named exports, as they are easier to use with less boilerplate, but I kept the default export in `signpdf.ts`, so it can be used exactly in the same way as before. Compiled output in `dist` is pure JS code and  typescript definitions are in corresponding `*.d.ts` files.

`node-forge` has also its TS definitions and after applying them, I could see potential problems in the code, just from the type-safety checks. I did not try to solve these issues, in such cases I just used anonymous type `any`.

Few years ago we have also been using Babel to compile ES6 code, but now after 3 years with TS I have found TypeScript configuration as much easier to setup with less dev dependencies. Testing with `ts-jest` worked out-of-the box and all your tests pass.

Have a look and if you would like to switch to TS let me know, I am ready to help.

Would you like to see it as PR or just browsing my [fork](https://github.com/moravcik/node-signpdf) is ok?

**Comment by vbuch** [comment]
I like the additional info it gives with TS. What I'm affraid could happen is lose some of the contributors because some people won't be willing to write TS.

**Comment by moravcik** [comment]
Yes, this is good point, but you can also gain some more contributors, who are willing to write in TS :)

Last month I was on ReactiveConf in Prague, and every second session was about advantages of writing the code in TypeScript. I would say that more-less all the JS world is moving toward writing the code in TS, but at the end of the day it is still old good JS with additional type definitions - allowing to write cleaner and less-buggy code, which is common problem of pure JS code.

**Comment by vbuch** [comment]
I've started some restructuring of the code that will eventually produce 2.0. Once I have things going, I will be glad to convert to TS if you would help.

**Comment by moravcik** [comment]
Yes, I will be glad to help, just let me know. Do you plan to use some monorepo tool for handling multiple packages, like [Lerna.js](https://lerna.js.org/)?

**Comment by vbuch** [comment]
I've only seen lerna so I was indeed thinking of using it. But I'm still far away from having separate packages. It's still just an idea.
