### ISSUE TITLE
Error 4002 PDF might contain errors in Digital Signature

### ISSUE THREAD

**Issue by hmpvillegas** [vbuch/node-signpdf#48]
I used the fluent reports in generating the PDF file then apply the digital Signature, The function works but I received the error when I tried to click See Signature version and it says ERROR 4002
"Malformed drawing instructions: Syntax error. Page content violates the grammar for page content definition. For example, the instruction might specify drawing a square but the syntax for doing it is incorrect." Doing this with the pdfkit as PDF generator didnt show any errors like this but however I wanted to use FLUENT REPORTS but this error keep showing up.

**Comment by vbuch** [comment]
I didn't know what flient reports is before this issue. I see it is something that uses the lib as dependency. If you could try the code from #57 it would be really nice. Other than that I cannot help much, unless you provide sample PDF that fails.
