### ISSUE TITLE
Blank pdf after signing

### ISSUE THREAD

**Issue by z-h-z-h** [vbuch/node-signpdf#56]
I investigated this bug and found that after signing the PDF file will be empty if it contained any link to website. Also, if the link href contain # instead of address (like http://google.com) everything will be fine.

```
 try {
            output = plainAddPlaceholder({
                pdfBuffer: fs.readFileSync(filename),
                reason: reason || 'my signature',
                signatureLength: 8192
            });
        } catch (e) {
            console.log('Error during adding placeholder');
            console.log(e.message);
            return response
                .status(500)
                .send({
                    message: 'Error during adding placeholder',
                    fn: plainAddPlaceholder ? plainAddPlaceholder.toString() : '-',
                    error: e.message,
                    trace: JSON.stringify(e.trace)
                });
        }
        try {
            const signedPdf = signer.sign(output, fs.readFileSync(cert));
            fs.writeFileSync(__dirname + '/last.pdf', signedPdf);
            fs.writeFileSync(filename, signedPdf);
            const {signature, signedData} = extractSignature(signedPdf);
            console.log(`Successfully signed ${filename}`);
            return response
                .send({ message: 'ok' });
        } catch (e) {
            console.log('Error during singing PDF');
            console.log(e.message);
            return response
                .status(500)
                .send({
                    message: 'Error during singing PDF',
                    error: e.message,
                    trace: JSON.stringify(e.trace)
                });
        }
```

**Comment by vbuch** [comment]
Is it blank after signing or after adding a placeholder? Can you add an example PDF here? @z-h-z-h

**Comment by z-h-z-h** [comment]
[test.pdf](https://github.com/vbuch/node-signpdf/files/4128810/test.pdf)

**Comment by vbuch** [comment]
Confirmed. Just checked it. `plainAddPlaceholder` messes it up. Haven't found the reason yet.

**Comment by vbuch** [comment]
@z-h-z-h I have created a working version of the buggy function but need to cover it with tests so can't merge yet.

**Comment by vbuch** [comment]
#57 is now in 1.2.2. Please confirm if the issue is resolved.

**Comment by AuspeXeu** [comment]
I am on 1.2.2 and have the same issue. Signing my PDF spits out only blank pages.

**Comment by vbuch** [comment]
Can you, again, attach a source PDF and any intermediates you may. This would assist in finding the issue.

**Comment by AuspeXeu** [comment]
The content of my PDFs is sensitive, cannot disclose. Sorry :/

**Comment by vemundeldegard** [comment]
Having the same issue. The first page is blank, the second one is not.

**Comment by vbuch** [comment]
@vemundeldegard can you attach an example PDF? Also if you could try what's in #59 ... @AuspeXeu you as well.

**Comment by vbuch** [comment]
1.2.3 is out in npm. Hope it fixes this issue.

**Comment by AuspeXeu** [comment]
Happy to confirm that this is resolved for me with the latest version :)

**Comment by ZaunSupremoXV** [comment]
Could you share the code used in the question?

**Comment by parceadl** [comment]
@AuspeXeu Hi, what version works for you? our first page is blank only in acrobat but we are in 1.5.0. thanks

**Comment by AuspeXeu** [comment]
I am on the latest version and that's working fine for me.
