### ISSUE TITLE
Could not find ByteRange placeholder

### ISSUE THREAD

**Issue by arpitagrawal0000** [vbuch/node-signpdf#60]
HI I am trying to sign a pre-generated pdf using node-signpdf and I am getting this error again and again. here is my code:-

```
const signer = require('node-signpdf').default;

function test() {
let pdfBuffer =  fs.readFileSync('./Foo.pdf'); 
let cert =  fs.readFileSync('./certificate.p12');

 let  test = signer.sign(pdfBuffer, cert);
  console.log(test, "response")
}
test();
```

I am getting below error - 

```
SignPdfError: Could not find ByteRange placeholder: /ByteRange [0 /********** /********** /**********]
    at SignPdf.sign (/home/hp/app/node_modules/node-signpdf/dist/signpdf.js:53:13)
    at test (/home/hp/app/index.js:96:21)
    at Object.<anonymous> (/home/hp/app/index.js:100:1)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  type: 3
```

**Comment by vbuch** [comment]
Does Foo.pdf contain a ByteRange placeholder?

**Comment by arpitagrawal0000** [comment]
yes Foo.pdf contain a ByteRange placeholder, in fact I have tried with the pdf you have provided in your test cases i.e w3dummy.pdf but it didn't worked.

**Comment by vbuch** [comment]
Check the repo out, `yarn && yarn test`.

**Comment by arpitagrawal0000** [comment]
can you please provide a working example since I am unable to use this library properly, maybe it's an import issue since I know your test cases are working fine.

**Comment by HeberLemus** [comment]
im having a similar problem with just passing a pdf in. 

it took me a bit to figure out how to even set this up as i wish actual examples were available instead of trying to figure out the bits needed from the test files.

my current stopping point is
`
'use strict';
const fs = require('fs');
const signPdfLib = require('node-signpdf');
const SignPdf = signPdfLib.SignPdf;
const signer = new SignPdf();

signer.sign(
    fs.readFileSync('./TestDocument.pdf'),
    fs.readFileSync('./dummycert.p12')
);
`

i too however am getting the error in this issue ticket, and i believe i need to run what is done here:
https://github.com/vbuch/node-signpdf/blob/7145a7e2265d5063ef2647f286c5644abbf21a7d/src/signpdf.test.js#L48

what i dont get is how to reference the functions in the helper folder as they are not available as part of the default exports. trying to require them via a node_modules/ path isnt clean either

**Comment by mkrishnappa** [comment]
@HeberLemus 
to access pdfkitAddPlaceholder you need to reference the helpers as shown below:
const pdfkitAddPlaceholder = require ('node-signpdf/dist/helpers').pdfkitAddPlaceholder;
and then you can call the function
const refs = pdfkitAddPlaceholder({ 
. . . 
)};

But looking at your code, I think you are reading a pdf that is already created.
So you will need to use:
const {plainAddPlaceholder} = require ('node-signpdf/dist/helpers');
and then 
pdfBuffer = fs.readFileSync('./TestDocument.pdf');
pdfBuffer = plainAddPlaceholder({
            pdfBuffer,
            reason: 'Xyz',
            signatureLength: 1612
        });
const signedPdf = obj1.sign(            
            fs.readFileSync(PATH_TO_PDF_FILE),
            fs.readFileSync(PATH_TO_P12_CERTIFICATE),
            {passphrase: 'password'}
        );

My understanding is, pdfkitAddPlaceholder is used to add the placeholder when the pdf was created using pdfkit.

**Comment by HeberLemus** [comment]
decided to wait for more updates on this library before trying again, running into two issues with two different pdfs

```
'use strict';
const fs = require('fs');
const signer = require('node-signpdf').default;
const {plainAddPlaceholder} = require ('node-signpdf/dist/helpers')

let pdfBuffer = fs.readFileSync('./test.pdf');
let cert = fs.readFileSync('./test.p12');

pdfBuffer = plainAddPlaceholder({
    pdfBuffer,
    reason: 'Xyz',
    signatureLength: 1612
});

let test = signer.sign(pdfBuffer, cert, {passphrase: 'test'});
console.log('test? ', test);
```

for one pdf the error i get it:

```
    throw new _SignPdfError.default('A PDF file must end with an EOF line.', _SignPdfError.default.TYPE_PARSE);
    ^

SignPdfError: A PDF file must end with an EOF line.
```

for the second test pdf, its: 

```
const isContainingPrev = infos.split('/Prev')[1] != null;
                                 ^

TypeError: Cannot read property 'split' of undefined
```

im still very unsure of what im doing and agree with @arpitagrawal0000 that it would be far better to have a real example structure of what the base code should look like at the minimum. the test files are confusing to understand.

**Comment by vbuch** [comment]
PDF is quite an extensive spec. Without example files, you wont get good answers. It could be anything thats wrong. The first error you refer to usually happens with PDF 1.7 files. So... Give example PDF files to get betterbresponse, please.

**Comment by Yzhibin** [comment]
I encounter similar problems. One PDF file gives me 
```
/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:55
  const isContainingPrev = infos.split('/Prev')[1] != null;
                                 ^
TypeError: Cannot read property 'split' of undefined
    at getXref
```

and the same PDF, after filled in text and image using Acrobat, it gives `A PDF file must end with an EOF line.` error. If I manually feed in a `\n` before `%%EOF`, it goes to the first error, `infos` undefined.

A hacky workaround I did is to take screenshot of the pdf can convert back to pdf using Mac Preview. But this clearly is not a solution for my app.

**Comment by RichardBray** [comment]
I was having this issue:
```
const isContainingPrev = infos.split('/Prev')[1] != null;
```

But I fixed it by turning off object streams in my pdf creation tool. If you're using PDF-LIB.js this should help you out:

https://github.com/Hopding/pdf-lib/issues/541
