### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by arpitagrawal0000** [vbuch/node-signpdf#61]
can anyone help why I am getting this issue? 
here is my code:-

```
const signer = require('node-signpdf').default;
const  {plainAddPlaceholder} = require('node-signpdf/dist/helpers');

const action = async () => {
var pdfBuffer = fs.readFileSync('./test.pdf');
 pdfBuffer = plainAddPlaceholder({
    pdfBuffer,
    reason: 'I am the author',
    signatureLength: 1612,
  });
let p12Buffer = fs.readFileSync('./certificate.p12')
let pdf = signer.sign(pdfBuffer, p12Buffer);
fs.writeFileSync(__dirname + '/result.pdf', pdf);
}

action();
```

and i am getting this error.

> (node:9110) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
>     at getXref (/home/hp/project/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:55:34)
>     at getFullXrefTable (/home/hp/project/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:79:25)
>     at readRefTable (/home/hp/project/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:100:25)
>     at readPdf (/home/hp/project/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readPdf.js:31:46)
>     at plainAddPlaceholder (/home/hp/project/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/index.js:54:37)
>     at action (/home/hp/project/index.js:92:14)
>     at Object.<anonymous> (/home/hp/project/index.js:105:1)
>     at Module._compile (internal/modules/cjs/loader.js:1157:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
>     at Module.load (internal/modules/cjs/loader.js:1001:32)
> (node:9110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:9110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>

**Comment by vbuch** [comment]
Without a PDF that fails, I doubt it that someone would help.

**Comment by dipedro** [comment]
@arpitagrawal0000 you are use a async function. so you have use await before call the method sign.

**Comment by zerobytes** [comment]
Here goes a pdf that fails, for me. Same error, same case. pdf that 
[pdf-that-fails.pdf…]()


@dipedro i doubt that your comment is correct, as there is no promise return in none of the methods.

**Comment by vbuch** [comment]
Yup. plainAddPlaceholder is synchronous so that's not the issue.

@zerobytes bad link?

**Comment by nfcaballaro** [comment]
Hi! check if your document is linearized, please visit: [https://www.pdftron.com/blog/pdf-format/what-is-pdf-linearization/](url)
The bug that exists is when the split is made, the "trailers" section is not found. Then it fails.

/home/hp/project/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js
` const [objects, infos] = refTable.toString().split('trailer');
`

**Comment by ankology** [comment]
Same error here.. PDF that fails [PDF 140mb](https://drive.google.com/open?id=0B53m7IA4HRpOVlhNdWxzdUtmMXc)
Error: Cannot read property 'split' of undefined [readRefTable.js#L48](https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/plainAddPlaceholder/readRefTable.js#L48)

**Comment by nfcaballaro** [comment]
@ankology if you edit the document, you can see in the first lines that your document is linearized

%PDF-1.5
%âãÏÓ
1028 0 obj
<</Linearized 1/L 142559740/O 1031/E 414421/N 242/T 142558182/H [ 490 812]>>
endobj

**Comment by Danny626** [comment]
Hi! 
Continuing with the thread of the topic, I have the same error with this pdf file, please if you could give me a hand I would really appreciate it.

Here is the pdf file:
[descarga.pdf](https://github.com/vbuch/node-signpdf/files/4670281/descarga.pdf)

The code used to sign:

```
    const p12Buffer = fs.readFileSync('./assets/certificados/certificate.pfx');
    let pdfBuffer = fs.readFileSync('./assets/pdfEntrada/descarga.pdf');
    pdfBuffer = plainAddPlaceholder({
        pdfBuffer,
        reason: 'I have reviewed it.',
        signatureLength: 1612,
    });
    pdfBuffer = await signer.sign(
        pdfBuffer,
        p12Buffer,
        {passphrase: 'password'},
    );
```

and i am getting this error.

> (node:8496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at getXref (C:\Users\danie\Proyectos\firmaDig_backend\helpers\plainAddPlaceholder\readRefTable.js:48:36)
    at getFullXrefTable (C:\Users\danie\Proyectos\firmaDig_backend\helpers\plainAddPlaceholder\readRefTable.js:77:27)
    at readRefTable (C:\Users\danie\Proyectos\firmaDig_backend\helpers\plainAddPlaceholder\readRefTable.js:99:27)
    at readPdf (C:\Users\danie\Proyectos\firmaDig_backend\helpers\plainAddPlaceholder\readPdf.js:22:22)
    at plainAddPlaceholder (C:\Users\danie\Proyectos\firmaDig_backend\helpers\plainAddPlaceholder\index.js:36:18)
    at firmarPDF2 (C:\Users\danie\Proyectos\firmaDig_backend\app.js:231:17)
    at procesoCompleto (C:\Users\danie\Proyectos\firmaDig_backend\app.js:55:11)
    at C:\Users\danie\Proyectos\firmaDig_backend\app.js:34:5
    at Layer.handle [as handle_request] (C:\Users\danie\Proyectos\firmaDig_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\danie\Proyectos\firmaDig_backend\node_modules\express\lib\router\route.js:137:13)
(node:8496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process 
with a non-zero exit code.

**Comment by ghoshpushpendu** [comment]
this issue occurs when you are using PDF-Lib to add or parse the PDF before the signing process.

{ useObjectStreams: false } to the save() method did the trick! in pdf-lib
