### ISSUE TITLE
Second page

### ISSUE THREAD

**Issue by hmpvillegas** [vbuch/node-signpdf#63]
Can you please help me with example to signed the pdf in the second page to nth page, would appreciate it, thanks

**Comment by BaruchHeroApps** [comment]
Hey @hmpvillegas  how you insert a signature on pdf?

**Comment by vbuch** [comment]
But a digital signature (pades) is something that is only needed once per document. It doesn't even need to be visible. If you are looking for ways to add an image/other visual to a pdf, this is not the place.

**Comment by hmpvillegas** [comment]
yup, im curious on the rect coordinates that was shown in this signature, if the default is the 1st page, then it is possible to second , nth page.

**Comment by vbuch** [comment]
Yes. This is possible. See here: https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/pdfkitAddPlaceholder.js#L70
This is where the widget (the rect) is added to the current page. So if you want to go to another page I think there was pdfdoc.switchToPage(x). If you add the annots/widget/rect there, you will get it on page 123. So the same applies to any other tool for creating/editing pdfs. As long as you can edit pages other than the first one, you can add the thing there.

**Comment by hmpvillegas** [comment]
actually its correct, but if it is in the pdfkitplaceHolder, however I am using the plainAddplaceholder. I still got it, thank you the help.
