### ISSUE TITLE
Support of ECDSA Certificate

### ISSUE THREAD

**Issue by joelviel** [vbuch/node-signpdf#65]
For the moment, only RSA certificates are supported (forge dependency constraint)
Any plan to support ECDSA certificate?

**Comment by vbuch** [comment]
Not planned. Would love PR.

**Comment by phutaneVinayak** [comment]
@vbuch Hi,

I wanted to support other then p12 certificate. i tried but either is stuck at some issue or failed. i am trying it from past 15 days. can you give me some advice or is any other way to implement it ? using  node-signpdf | node-forge any other ?

**Comment by vbuch** [comment]
The current implementation is tied to node-forge. I would suggest you only use the PDF-editing code from this lib and replace the signature creation with whatever suits you. Then, if it looks like it can be integrated here, we can look at it. But.. check the lib out and make it work for you.
