### ISSUE TITLE
Question regarding embedded timestamp

### ISSUE THREAD

**Issue by j-tegen** [vbuch/node-signpdf#68]
Hi,

First of all - thank you for the work, it seems very promising.

I've cloned the repo and tried to figure out if there is any way to add an embedded timestamp using a TSA (Trusted timestamp authority). Currently when signing a document (for example in the test files), Adobe will show a warning that the "Signing time is from the clock on the signer's computer".

Is there any way to provide an embedded timestamp to the signature?
If not, is this something on your radar for future improvements?

**Comment by vbuch** [comment]
I was looking into the topic some time ago. I had bookmarked this thing https://www.timenotary.com/about/ but then life stopped me and... I cant say much more than that link.
Would be great if someone implemented that...

**Comment by vbuch** [comment]
Embedding a timestamp is quite related to PAdES and issue #71 Just linking here.
