### ISSUE TITLE
AdES digital signature

### ISSUE THREAD

**Issue by ioprea** [vbuch/node-signpdf#71]
**Describe the bug and the expected behaviour**
I have been trying out the lib, but I am not sure whether it generates PAdES compliant signatures. I have tried validating it here https://ec.europa.eu/cefdigital/DSS/webapp-demo/validation which seems like the only tool for PAdES validation but I have been getting 'The signature/seal is not a valid AdES digital signature!'. I don't know if I am doing something wrong or if that's the expected behaviour.

**Is it a bug in signing or in the helpers?**
Haven't seen anything similar

**To Reproduce**
Sign a document using the library, I have tested it on a dummy.pdf nothing special with different certificates. Just upload the original and signed file to the validation platform specified above. It offer detailed information regarding the signature
<img width="857" alt="Screenshot 2020-04-27 at 12 23 20" src="https://user-images.githubusercontent.com/30468011/80356269-e4dbf300-8881-11ea-9630-cd59de3f5993.png">

**Comment by vbuch** [comment]
True. We have not created AdES with node-signpdf but rather only an ES. AFAIK the only thing you need more is a trusted issuer. But I havent gone through the details of that. Some code changes may be needed if we want to produce PAdES. Someone needs to research this.
I think #70 is about the same issue.

**Comment by vbuch** [comment]
BTW Reading through [the spec](https://www.etsi.org/deliver/etsi_ts/102700_102799/10277801/01.01.01_60/ts_10277801v010101p.pdf), I think the signed documents produced here are PAdES Basic (section 5.1)

**Comment by ioprea** [comment]
Indeed it is PAdES Basic, over the next few weeks I will be looking over generating an AdES signature, it seems like there is only a Java lib that does it, will try to implement it in nodejs.

**Comment by kas84** [comment]
@ioprea did you manage to do it? What’s the java library that does it?

**Comment by agustif** [comment]
Interested on seeing this through, maybe I can contribute? Let me know where you left it of @ioprea if you wish !

**Comment by hmpvillegas** [comment]
The more appropriate question/ to find is at least url of the timestamp server, if u have a plan/purchase use the url if not find a url of a free version, if u guys find a link, kindly reply or link it here, cause the code to add the time stamp is much more simple.

**Comment by HamidOsouli** [comment]
Same issue here.

**Comment by sanchezandoni** [comment]
Hi! Any news on this issue?
