### ISSUE TITLE
PKCS#12 MAC could not be verified. Invalid password?

### ISSUE THREAD

**Issue by unuhmed** [vbuch/node-signpdf#80]
i created one CA with password, but when i want to read this certificate in buffer but i can't
how to enter password aim to open this certificate ?
Thanks you
![Capture](https://user-images.githubusercontent.com/66678287/84753543-69fca200-afbf-11ea-89f2-d8a0382ac7f1.PNG)

**Comment by unuhmed** [comment]
> How did you solve the problem?

add passphrase option, but instead if you have this error, it seams the bug came to NODE-FORGE and my certificate wasn't good.
If you want to fix this bug 1) try to change your certificate with PEM and after p12 format
2)or generate your certificate with openssl

**Comment by jhondavila** [comment]
algun ejemplo de como generar el certificado sin contraseña desde mi pem
