### ISSUE TITLE
signer.sign is not a function

### ISSUE THREAD

**Issue by ZaunSupremoXV** [vbuch/node-signpdf#82]
Tentei executar o modelo de [teste ](https://github.com/vbuch/node-signpdf/blob/develop/src/signpdf.test.js)adaptando para minha necessidade, mas não funcionou. Tentei testar de maneira simples, mas não teve resultado também.  Como faço para funcionar?
![Captura de Tela (7)](https://user-images.githubusercontent.com/67069017/84936080-18801000-b0b0-11ea-86c6-ce9ba3788d13.png)
)

**Comment by unuhmed** [comment]
try instead of signer.sign

pdfBuffer=signer.default.sign(pdfBuffer, p12Buffer);

**Comment by ZaunSupremoXV** [comment]
Thank you, it worked.
