### ISSUE TITLE
Error: pdfkitAddPlaceholder is not defined

### ISSUE THREAD

**Issue by ZaunSupremoXV** [vbuch/node-signpdf#85]
![Captura de Tela (9)](https://user-images.githubusercontent.com/67069017/85060251-4f6f2800-b17b-11ea-9ecb-19cde701acd6.png)
![Captura de Tela (10)](https://user-images.githubusercontent.com/67069017/85060256-50a05500-b17b-11ea-96ea-9e4ed84fe52d.png)

**Comment by ifuschini** [comment]
try something of this:

import pdfkitAddPlaceholder from 'node-signpdf/dist/helpers/pdfkitAddPlaceholder';

**Comment by ZaunSupremoXV** [comment]
> tente algo disso:
> 
> importar pdfkitAddPlaceholder de 'node-signpdf / dist / helpers / pdfkitAddPlaceholder';


I changed the code and am running it on adonisJs. I changed the code, made it generate the PDF with the space for signature so that later you can sign the PDF. An error appears saying that fonts are undefined.

![Captura de Tela (7)](https://user-images.githubusercontent.com/67069017/86121148-e4432100-baab-11ea-92da-a9f039aa584e.png)
![Captura de Tela (8)](https://user-images.githubusercontent.com/67069017/86121150-e5744e00-baab-11ea-9f60-4b110c8336c1.png)
![Captura de Tela (9)](https://user-images.githubusercontent.com/67069017/86121152-e5744e00-baab-11ea-94ee-972d1a43bbd9.png)
