### ISSUE TITLE
pdfkitAddPlaceholder fails using pdfkit 0.11.0

### ISSUE THREAD

**Issue by vladh1** [vbuch/node-signpdf#88]
**Describe the bug and the expected behaviour**
pdfkitAddPlaceholder fails using pdfkit 0.11.0 with the error: "Cannot read property 'fonts' of undefined"

**Is it a bug in signing or in the helpers?**
Issue is related to the pdfkitAddPlaceholder helper

**To Reproduce**
```
const signer = require('node-signpdf').default;
const pdfkitAddPlaceholder = require('node-signpdf/dist/helpers/pdfkitAddPlaceholder').default;
const fs = require('fs');
const PDFDocument = require('pdfkit');
const pdf = new PDFDocument({
	autoFirstPage: true,
	size: 'A4',
	layout: 'portrait',
	bufferPages: true,
});
pdf.info.CreationDate = '';

// Add some content to the page
pdf
	.fillColor('#333')
	.fontSize(25)
	.moveDown()
	.text('HELLO WORLD');

// Collect the ouput PDF
// and, when done, resolve with it stored in a Buffer
const pdfChunks = [];
pdf.on('data', (data) => {
	pdfChunks.push(data);
});
pdf.on('end', () => {
	console.log("pdfDoc.end");
	let pdfBuffer = Buffer.concat(pdfChunks);
	let signedPDF = signer.sign(pdfBuffer, fs.readFileSync('pdf/cert/certificate.pfx'));
	fs.writeFileSync('pdf/document.pdf', signedPDF);
});

// Externally (to PDFKit) add the signature placeholder.
const refs = pdfkitAddPlaceholder({
	pdf,
	pdfBuffer: Buffer.from([pdf]),
	reason: 'I am the author'
});
// Externally end the streams of the created objects.
// PDFKit doesn't know much about them, so it won't .end() them.
Object.keys(refs).forEach(key => refs[key].end());

// Also end the PDFDocument stream.
// See pdf.on('end'... on how it is then converted to Buffer.
pdf.end();
```

**Comment by copperwall** [comment]
This isn't a total solution, but I ran into this today and noticed that there's a new method on the `PDFDocument` instance called `pdf.initForm` that sets up an AcroForm, but the code in `pdfkitAddPlaceholder` doesn't copy all of the fields that pdfkit places on the initial AcroForm ref so when .end is called on the form it fails to find the fields originally placed on the form by pdfkit.

It looks like pdfkitAddPlaceholder needs to be updated to include those fields.
https://github.com/foliojs/pdfkit/blob/master/lib/mixins/acroform.js#L83

**Comment by vbuch** [comment]
https://github.com/vbuch/node-signpdf/issues/49

**Comment by copperwall** [comment]
Hey @vbuch I'm interested in working on this if that works for you.

**Comment by vbuch** [comment]
I dont have the time to do it, so you are more than welcome. Please create a separate helper for that as people with pdfkit10 will probably still want to use the available one.

**Comment by nayaras** [comment]
Any updates on this?

**Comment by eminoda** [comment]
pdfkit 更新并添加了一些方法，比如：initForm，导致 node-signpdf 中的 pdfkitAddPlaceholder 不能正常工作！

你可以单独写一个 pdfkitAddPlaceholder 方法，把一些异常错误做个处理：

```js
// ...
const pdf = new PDFDocument({
      autoFirstPage: false,
      size: 'A4',
      layout: 'portrait',
      bufferPages: true,
    })
    pdf.initForm() // 注意！！！
    pdf
      .addPage()
      .fillColor('#333')
      .fontSize(25)
      .text('Hello PdfDocument ' + Date.now())
      .save()
// ...
```
```js
// your pdfkitAddPlaceholder.js
// ...
let form;

if (!isAcroFormExists) {
  // Create a form (with the widget) and link in the _root
  form = pdf.ref({
    Type: 'AcroForm',
    SigFlags: 3,
    Fields: [...fieldIds, widget],
    // 注意！！！
    DR: {
      Font: {}
    }
  });
} else {
// ...
```

**Comment by DevMesh18** [comment]
I am getting error :

```
const pdfBufferToSign1 = pdfkitAddPlaceholder({
    pdfDoc,
    pdfBytes,
    subFilter: SUBFILTER_ETSI_CADES_DETACHED,
    reason          : 'I have reviewed it.',
    signatureLength : 15544,
   
  });
```

TypeError: Cannot read property 'ref' of undefined
    at pdfkitAddPlaceholder (D:\workspace\DPI-workspace\UI\soap-test\node_modules\node-signpdf\dist\helpers\pdfkitAddPlaceholder.js:37:25)
    at main (D:\workspace\DPI-workspace\UI\soap-test\pdf-test.js:18:26)
