### ISSUE TITLE
Error when signing with certificate containing latin characters

### ISSUE THREAD

**Issue by wesleimarinho** [vbuch/node-signpdf#89]
When a certificate containing latin characters is used, the signature is corrupted (or in some PDF readers, such as Foxit Reader, it says the document has been altered since signature).

I imagine it's not a problem with the helpers.

Example certificate is attached, it has the brazilian state name `"São Paulo"`: [latin.zip](https://github.com/vbuch/node-signpdf/files/4982274/latin.zip) - the provided sample certificate has a blank password.

The same behavior has been identified using any certificate data containing latin characters.

**Comment by Kyryn** [comment]
We have same problem with latin characters ěščřžýáíé

**Comment by vbuch** [comment]
Can't remember from top of my head but probably an assumption of utf-8 is made somewhere in the code. The placeholder should be irrelevant as it doesn't care of certificates. Certificates come when it comes to signing. So it is either in the signing code (which is roughly 200 lines of easy to read code) or in node-forge (which could be quite an issue to debug).

**Comment by wesleimarinho** [comment]
I think it is not related to placeholders. I face the same behavior when using the mentioned certificates and `pdf-lib` to add the placeholders.

**Comment by LuanMaik** [comment]
I give up and created the solution using Quarkus (java) and PDFBox lib.
This link show how to implement the solution in java: https://jvmfy.com/2018/11/17/how-to-digitally-sign-pdf-files/
