### ISSUE TITLE
Its about time to level up the PDF standard.

### ISSUE THREAD

**Issue by hmpvillegas** [vbuch/node-signpdf#91]
I think this package should be able to validate at least intermediate level from docusign and euro validation. Because of covid, the level of PDF required at least to be able to validate from those 2 mention from above. without this, this package of pdf signing wont be even trusted in companies etc. Hope someone will do this and I will be gladly to help.

**Comment by hmpvillegas** [comment]
@therpobinski  have you tried or at least implement to your package?

**Comment by therpobinski** [comment]
I do not understand what you want, if it is to validate the signed document. In other words, validating signatures, in my opinion, is a different step, you can use other libraries to validate signatures if you think it is convenient for your projects, you can implement what you need in your project. I think the components should not allow you to do everything you need, but something specific to continue your development. In my case, I only use this component to sign, and if I want to validate I do another step. The library serves me very well.

**Comment by hmpvillegas** [comment]
Ohh my bad,  the only fault for not passing the validate in those websites that i mention above is not using PADES format.  I was just asking if u implement the PADES in your package.

**Comment by hmpvillegas** [comment]
if possible can I have an example of your signed pdf ?

**Comment by vbuch** [comment]
We spoke about this in another issue. The library supports PAdES Basic. The next needed step is timestamping. If anyone wants to give it a shot, PRs will be welcome.

**Comment by agustif** [comment]
> We spoke about this in another issue. The library supports PAdES Basic. The next needed step is timestamping. If anyone wants to give it a shot, PRs will be welcome.
> 
> Edit: see issue #71

I would love to open a PR to see this through

**Comment by vbuch** [comment]
All I can help with: https://github.com/vbuch/node-signpdf/issues/68#issuecomment-610034107

**Comment by agustif** [comment]
Some free alternatives to timenotary, not sure if paid is obligatory for pades purposes though

https://www.freetsa.org/index_es.php
https://gist.github.com/Manouchehri/fd754e402d98430243455713efada710

Will try to take a stab at implementing this soon!

**Comment by hmpvillegas** [comment]
I think that this package does not follow the PDF ISO 32000 Standard, am I right ?
